<h1 style = "text-align:center; color:red"> Python </h1>

Python is a high level, cross platform language using interpreter.

## 1. Python Interpreter Environment

--------------------------------------
## 2. Intro

- Python is casesensitive. <br>
- Indexing in Python is based-0.<br>
- All keywords of python are lowercase.<br>
- All intervals in Python are close-open ( [start, end) ), like interval indexing

- Everything in Python is object. 

Objects in Python classify into two groups:
1. mutable : This groups can change after defining (changing of part of them) like lists.
- mutable objects pass by-reference. 
2. immutable : This groups cannot be changed partly. For changing them, we must assign them a whole new value like strings
- immutable objects pass by-value.

### 2.1. Variables

##### 2.1.4.4. string functions

In [17]:
s = "SalaMla"
print(s.find("la"))   # if input string of function exists in the string, returns index of first char of first matching string.
print(s.find("ali"))  

print(s.count("Sa"))        # returns # of repeatance of input string in the string (string s).
print("aaaaa".count("aa"))  # This function do not count overlapping.

print(s.removeprefix("Sa"))    # if input string exists at the begining of the string s, returns a string without input prefix. if input string do not exist at begining of main string, returns main string.
print(s.removesuffix("Mla"))   # if input string exists at the end of the string s, returns a string without input prefix. if input string do not exist at the end of main string, returns main string.

print(s)

2
-1
1
2
laMla
Sala
SalaMla


- all function of strings do not change the main string because string is immutable, so they returns value

-------------------------------
### 2.2. I/O 

#### 2.2.1. Input

In [ ]:
import re

# Python always gets all line as input in type of String
yourName = input("Enter your name: ") # The string in () 
yourAge = int(input("Enter your age: "))

p, d = re.split(' ', input()) # gets two string in one line which seperates form each other by space
p = int(p)
d = int(d) 

#### 2.2.2. Output

In [8]:
print("helloWorld") # print instruction moves to next line after printing as default. 

print("Salam", end = " ") # default of "end" is \n . 
print("Khoobi")

helloWorld
Salam Khoobi


---------------------------
### 2.3. namespace

<div style = "direction:rtl">
یک سیستم نامگذاری برای متمایز کردن نام خصوصیت‌ها و متغیرها استفاده می‌شود. یک کلاس و یا همچنین متغیرهای محلی (local) هر تابع نیز تشکیل یک فضای نام می‌دهند. به طور مثال فرض کنید در یک کلاس چند دانش‌آموز با نام رضا وجود دارد. در این صورت برای متمایز کردن آن‌ها به نام خانوادگی‌شان نیز نیاز داریم. به طور مثال اگر فرد موردنظر شما رضا کریمی باشد، حتما باید نام خانوادگی او را نیز صدا بزنید. اگر فقط نام او را صدا بزنید، بیشتر از یک نفر به شما پاسخ خواهند داد. چنین چیزی درباره فضای‌نام نیز کاملا صدق می‌کند. به عبارتی دو شئ می‌توانند هم اسم باشند ولی در دو فضای نام متفاوت قرار گرفته باشند، در این صورت هیچ ربطی به هم ندارند.
<br>
مثال زیر را در نظر بگیرید:
</div>

In [ ]:
def f1():
    x = 100
    print(x)

def f2():
    x = 200
    print(x)

<div style = "direction:rtl">
در مثال بالا، در هر دو تابع، متغیر x وجود دارد، ولی چون هر کدام از آن‌ها یک فضای‌ نام جدا هستند؛ پس می‌توان از این متغیر در هر دو تابع استفاده کرد، بدون اینکه عملکرد تابع دیگری مختل شود.
</div>

#### 2.3.1. kinds of namespace

<div style = "direction:rtl">
    فضای نام‌ها در زمان‌های متفاوتی ساخته می‌شوند و دارای طول‌ عمر‌های متفاوتی هستند.<br>
    <ol>
        <li>
    فضای‌نام built-in (فضای نام توابع، خطا‌ها، تولید‌کننده‌ها و ... پیش‌فرض پایتون) وقتی ساخته می‌شود که مفسر پایتون شروع به کار می‌کند و تا تمام شدن برنامه باقی‌‌ می‌ماند.<br>
        </li>
        <li>
    فضای‌ نام عمومی (module) وقتی شروع می‌شود که مفسر وارد تعریف آن شود و تا وقتی که مفسر از آن خارج شود باقی می‌ماند.<br>
        </li>
        <li>
    فضای نام‌ محلی‌ِ یک تابع وقتی که مفسر وارد تابع می‌شود (زمانی که یک تابع فراخوانی شود) ساخته می‌شود و وقتی تابع مقداری را برگرداند و یا دچار یک خطا شود (خطایی که درون تابع مدیریت (handle) نشده باشد) از بین می‌رود. بنابراین هر کدام از لایه‌های توابع بازگشتی دارای فضای‌ نام محلی‌ جدایی هستند.
        </li>
    </ol>
</div>

--------------------------------------------
### 2.4. Scope (of objects)

<div style = "direction:rtl" >
    در پایتون برای تعریف محدوده (Scope) باید تمام دستورات درون آن محدوده را با فاصله بیش‌تر نسبت به دستور قبل از شروع محدوده بنویسیم (قبل از آن‌ها یک Tab اضافه می‌گذاریم). درواقع پایتون با فاصله، ساختار می‌یابد. در صورتی هم که این کار را انجام ندهیم مفسر خطا داده و برنامه اجرا نمی‌شود.
</div>

In [ ]:
x = 10
def f():
    if x % 2 == 0:
        print("even")
        pass
    else:
        print("odd")
        pass

<div style = "direction:rtl" >
    هم‌چنین در ادامه‌ی تمامی دستورات کنترلی در محدوده‌ی آن‌ها حتما باید دستوری برای اجرا نوشته شود (اگر محدوده خالی باشد خطای IndentationError برگردانده می شود). در صورتی که نخواهیم در محدوده‌ای چیزی اجرا شود، می‌توانیم دستور pass را به تنهایی در آن محدوده قرار دهیم. این دستور به مفسر می‌گوید بدون انجام هیچ کاری از این خط عبور کن.
    <br>
    <li>
    برای به اتمام رساندن یک scope  حتما از pass استفاده می کنیم.
    </li>
</div>

In [ ]:
def f():
    pass

#### 2.4.1. local scope

<div style = "direction:rtl">
درونی‌ترین محدوده که شامل متغیر‌های محلی می‌شود. به عبارتی متغیری که درون یک تابع تعریف می‌شود و فقط از درون همان تابع قابل دسترس باشد در این محدوده قرار دارد. به مثال زیر توجه کنید:
</div>

In [4]:
def f():
    xl = 100
    print(xl)
    pass
f()
print(xl)

100


NameError: name 'xl' is not defined

<div style = "direction:rtl">
متغیر xl بیرون از محدوده تابع در دسترس نیست.
</div>

#### 2.4.2. global scope

<div style = "direction:rtl">
وقتی متغیری درون این محدوده تعریف شود در جای‌‌جای فایل یا اسکریپت پایتونی مربوطه در دسترس می‌باشد. برای درک این موضوع به مثال زیر دقت کنید:
</div>

In [7]:
xz = 100
def f():
    print(xz)
f()
print(xz)

100
100


<div style = "direction:rtl">
متغیر x درون محدوده محلی تابع نیز در دسترس است.
</div>

<div style = "direction:rtl">
اگر نیاز به ساخت متغیر global دارید اما در محدوده‌ی محلی هستید، می‌توانید از کلمه کلیدی global استفاده کنید:
</div>

In [ ]:
def f():
    global x
    print(x)
x = 100
f()

#### 2.4.3. built-in scope

<div style = "direction:rtl">
توابعی مثل print() و id() به محض اجرای مفسر در تمامی نقاط اسکریپت یا فایل مربوطه قابل دسترس هستند که در فضای نام built-in قرار می‌گیرند. این یعنی شما می‌توانید این توابع را هرکجای کدتان استفاده کنید. در ضمن این محدوده دارای بیشترین طول عمر می‌باشد.
</div>

#### 2.4.4. non-local variables

<div style = "direction:rtl">
 حال نوبت به متغیرهای غیرمحلی می‌رسد:
<br>
کلمه کلیدی nonlocal برای دسترسی به متغیرهای درون توابع تودرتو استفاده می‌شود، هنگامی که متغیر تابع داخلی متعلق به تابع بیرونی است. برنامه زیر را در نظر بگیرید. اگر بخواهیم در تابع g به متغیر age که درون تابع f قرار دارد دسترسی داشته باشیم از کلمه کلیدی nonlocal استفاده می‌کنیم.
</div>

In [5]:
def f():
    name = 'mohammad'
    age = 10
    def g():
        name = 'saeid'
        nonlocal age
        age = 15
        print(name, age)
        pass
    print(name, age)
    g()
    print(name, age)
    pass

f()

mohammad 10
saeid 15
mohammad 15


<div style = "direction:rtl">
در مثال زیر، نحوه‌ی استفاده از متغیرهای local, globalو nonlocal را در کنار هم می‌بینید و می‌توانید مقایسه کنید.
</div>

In [9]:
def test():

    msg= "salam"

    def test_local():
        msg = "khoobi?"
        print("in function: " + msg)

    def test_nonlocal():
        nonlocal msg
        msg = "chetori?"
        print("in function: " + msg)

    def test_global():
        global msg
        msg = "chera?!"
        print("in function: " + msg)

    test_local()
    print(msg)
    test_nonlocal()
    print(msg)
    test_global()
    print(msg)

test()
print(msg)

in function: khoobi?
salam
in function: chetori?
chetori?
in function: chera?!
chetori?
chera?!


<div style = "direction:rtl">
ابتدا تابع test() صدا زده می‌شود؛ در این تابع، ابتدا تابع test_local() صدا زده می‌شود. در این تابع یک متغیر محلی تعریف شده و درخط بعد مقدار عبارت موردنظر چاپ می‌شود که برابر in function: khoobi? است (چون متغیر محلی است، پس تغییری در متغیر msg که در خط ۳ تعریف شده،‌ ایجاد نمی‌شود). و در نهایت نیز چون مقدار msg که در خط ۳ است تغییری نکرده، پس print خط ۲۰، مقدار salam را چاپ می‌کند.
<br>
پس از آن،‌ تابع test_nonlocal() صدا زده می‌شود. در این تابع یک متغیر غیرمحلی تعریف شده، به این معنی که هر مقداری که داخل این متغیر قرار دهیم،‌ داخل متغیر msg که در خط ۳ تعریف شده نیز قرار می‌گیرد. پس مقدار msg های خطوط ۳ و ۱۱ برابر chetori? می‌شود و در خط ۱۲،‌ عبارت in function: chetori? چاپ شده و چون مقدار msg خط ۳،‌ تغییر کرده پس print خط ۲۲، مقدار chetori? را چاپ می‌کند.
<br>
در نهایت تابع test_global() صدا زده شده و یک متغیر گلوبال در این تابع ساخته می‌شود. پس از آن، چون مقدار این متغیر در این تابع برابر chera?! قرار داده شده؛ پس عبارت in function: chera?! چاپ می‌شود. چون تابع test() خود دارای متغیر msg است،‌ پس در خط ۲۴، همان مقدار chetori? که قبلا درون آن قرار داشت،‌ چاپ می‌شود.
<br>
در نهایت اجرای تابع test() تمام شده و به سراغ خط ۲۷ می‌رویم. در این خط متغیر msg باید چاپ شود ولی در این محدوده، هیچ متغیری با چنین نامی وجود ندارد. پس در برنامه به دنبال محدوده‌ای می‌گردیم که متغیر msg به صورت global تعریف شده باشد، که این اتفاق در تابع test_global() و خط ۱۵ اتفاق افتاده است. پس مقدار chera?! چاپ می‌شود.
</div>

<div style = "direction:rtl">
این نکته حائز اهمیت است که محدوده‌ها به صورت متنی تعریف می‌شوند و ربطی به نحوه اجرا و یا اینکه تابع از کجا صدا زده شده ندارند. محدوده تابع که درون آن متغییر‌های محلی هستند فضای متنی جلوی تابع است و فضای نام عمومی بخشی‌ست که کد تابع در آن نوشته شده.
</div>

----------------------------------
### 2.6. Function

#### 2.6.1. function is an object

<div style = "direction:rtl" >
    در پایتون تابع یک شی‌ء کلاس‌-اول (first-class) است. فرض کنید یک تابع به نام f دارید، سپس متغیر g را برابر با f قرار می‌دهید. حالا g دقیقا مانند f عمل می‌کند. نوعی که پایتون برای توابع در نظر می‌گیرد function است.
</div>

<div style = "direction:rtl" >
    یک object در یک زبان first class هست اگر:
<br>وقتی در ران تایم بشه ایجادش کرد 
<br>خروجی یک تابع بتونه باشه
<br>ورودی یک تابع بتونه باشه
    <br>
    بر این اساس function در پایتون یک شی فرست کلاس است.
</div>

In [2]:
def f(a):
    return a
    pass


print(f(10))
g = f
print(g(10))
print(type(g))
print(f(f(9))) 
print(f(f)(9))     # f(f) = f

10
10
<class 'function'>
9
9


In [24]:
def f(g):
    g(10)
    return g


def g(a):
    print(a)
    pass


f(g)(100)  # equal to g(10) because f(g) returns g

10
100


<div style = "direction:rtl">
در مثال بالا ابتدا f(g) صدا زده می‌شود و ۱۰ چاپ می‌شود؛‌ سپس در خروجی تابع g برگردانده می‌شود و ۱۰۰ به آن ورودی داده می‌شود. بعد از آن عبارت ۱۰۰ چاپ می‌شود.
</div>

<div style = "direction:rtl">
هم‌چنین مانند بقیه اشیا با = انتقال داده‌ می‌شوند.
</div>

In [26]:
g = print
g("salam")

salam


#### 2.6.2. function can be defined anywhere.

<div style = "direction:rtl">
در پایتون در تمام محدوده‌ها (scope) می‌توان تابع تعریف کرد. در مثال زیر یک تابع تعریف می‌کنیم که لیستی از ضرایب را ورودی گرفته، سپس تابعی خروجی می‌دهد که محاسبه کننده یک چندجمله‌ای با همان ضرایب داده شده است.
</div>

In [28]:
def poly_builder(ls):
    def p(x):
        ret = 0
        for i in range(len(ls)):
            ret += ls[i] * (x**i)
        return ret
    return p

f = poly_builder([1, 1]) # x + 1
print(f(-1))
f = poly_builder([-2, 0, 1]) # x^2 - 2
print(f(5))

0
23


<div style = "direction:rtl">
ه کمک کد بالا و بسط تیلور یک تابع می‌سازیم که sin را تخمین می‌زند.
</div>

In [29]:
def poly_builder(ls):
    def p(x):
        ret = 0
        for i in range(len(ls)):
            ret += ls[i] * (x**i)
        return ret
    return p

import math

def fact(n):
    if n == 0:
        return 1
    return fact(n-1)*n

a = []
for i in range(0, 100):
    a.append(0)
    if i%2 == 0:
        continue
    a[i] = 1.0/fact(i)
    if int(i/2)%2 == 1:
        a[i] *= -1

sin = poly_builder(a)

print('math sin: ')
print(math.sin(math.pi/6))
print('our sin: ')
print(sin(math.pi/6))

math sin: 
0.49999999999999994
our sin: 
0.49999999999999994


#### 2.6.3. default values of function arguments

In [22]:
def f(a=0, b=1): # if some of arguments do not get value, default values are considered for those agruments
    return a+b
    pass
print(f(2, 3)) # 5
print(f(2)) # 3
print(f())  # 1

5
3
1


<div style = "direction:rtl">
توجه‌ کنید که متغیرهایی که مقدار پیش‌فرض ندارند باید قبل از دیگر متغیرها بیایند؛ در غیر این صورت خطای سینتکس دریافت می‌کنیم. به طور مثال برنامه زیر بعد از اجرا، خطا می‌دهد.
</div>

In [ ]:
def f(a=0, b):
    return a+b
    pass

<div style = "direction:rtl">
    کته مهم دیگر در مورد مقادیر پیش‌فرض این است که فقط یک بار مقداردهی و در حافظه ذخیره می‌شوند. سپس در فراخوانی‌های بعدی از آن مقادیر ذخیره‌شده استفاده می‌شود و ممکن است همان مقدار دلخواه را نداشته باشند. برای مثال کد زیر را ببینید:
</div>

In [23]:
def f(a, L=[]):
    L.append(a)
    return L
    pass
print(f(1)) # [1]

print(f(2)) # [1, 2]

print(f(3)) # [1, 2, 3]


[1]
[1, 2]
[1, 2, 3]


<div style = "direction:rtl">
    همان طور که می‌بینید ‍‍L یک بار محاسبه می‌شود و سپس در فراخوانی‌های بعدی همان L قبلی تغییر می‌کند. برای اجتناب از بروز این مشکل می‌توانیم مقدار پیش‌فرض متغیر را None در نظر بگیریم، سپس درون تابع در صورتی که مقدار None داشت مقدار دلخواه را به آن ا اختصاص دهیم. یعنی تابع بالا را می‌توان به شکل زیر تغییر داد.
</div>


In [24]:
def f(a, L=None):
    if L == None:
        L = []
        L.append(a)
        return L
        pass
    pass
print(f(1)) # [1]

print(f(2)) # [2]

print(f(2,f(1))) # [1, 2]

[1]
[2]
None


#### 2.6.4. Extra Arguments

<div style = "direction:rtl">
    فرض کنید می‌خواهیم تابعی بنویسیم که تعداد ورودی‌هایش مشخص نباشد. به عبارتی بتوان به تعداد دلخواه به آن ورودی داد. برای این کار می‌توانیم بعد از همه ورودی‌های تابع کلمه *args را اضافه کنیم. در این صورت همه ورودی‌های اضافی که دریافت می‌شود، در قالب یک tuple درون *args ذخیره می‌شوند. توجه کنید که اگر ورودی اضافی نداشته باشیم اندازه آن صفر می‌شود.
</div>

In [26]:
def f(a, *args):
    return args
    pass

print(f(2)) # ()

print(f(2, 1)) # (1,)

print(f(1, 2, 3)) # (2, 3)

()
(1,)
(2, 3)


<div style = "direction:rtl">
    توجه‌ کنید که لزومی ندارد اسم ورودی *args باشد و می‌تواند هر چیز دیگری که با * شروع می‌شود باشد.
    <br>
نوع دیگری از ورودی‌های اضافه که می‌توان به تابع داد، کلیدواژه‌ها هستند. نحوه استفاده از این ورودی‌ها تقریبا مانند لغت‌نامه است. به این صورت که در ورودی تابع به ازای هر متغیر که می‌خواهیم اضافه کنیم ابتدا اسمشو بعد از یک علامت مساوی، مقدارش را می‌نویسیم. در نهایت تمام این متغیرها در قالب یک لغت‌نامه در **kwargs که باید جزء ورودی‌های تابع باشد ریخته می‌شوند.
    <br>
برای مثال در زیر تابعی تعریف کرده‌ایم که ابتدا args را می‌گیرد و سپس kwargs و آن‌ها را چاپ می‌کند.
</div>

In [3]:
def f(*args, **kwargs):
    print(args)
    print(kwargs)
    pass
f(a=2) # ()
       # {'a': 2}

f(1, a=2) # (1,)
          # {'a': 2}

()
{'a': 2}
(1,)
{'a': 2}


In [4]:
f(1, a=2, 2)

SyntaxError: positional argument follows keyword argument (Temp/ipykernel_21624/755564894.py, line 1)

<div style = "direction:rtl">
    همان طور که می‌بینید اگر **kwargs بعد از ‍‍*args تعریف شود، حتما باید تمام ورودی‌های عادی ابتدا وارد شوند و در غیر این صورت مانند مثال آخر خطای سینتکسی دریافت خواهیم‌ کرد.
</div>

In [1]:
def printUsers(**users):
    for name,age in users.items():
        print(f"{name} is {age} years old")
        pass
    pass
printUsers(ali=21, mamadreza=18, mahdi=22)

ali is 21 years old
mamadreza is 18 years old
mahdi is 22 years old


<div style = "direction:rtl">
نام عضوی که لغت‌نامه درون آن ریخته می‌شود مانند *args مهم نیست. فقط باید با ** شروع شود. اما استاندارد توابع پایتون این است که این دو را به همین صورت نام‌گذاری کنیم.
</div>

#### 2.6.5. Unpacking

<div style = "direction:rtl">
    فرض کنید لیستی از مقادیر مختلف دارید که می‌خواهید تک تک مقادیر آن را به یک تابع بدهید. به طور کلی با استفاده از کاراکتر * می‌توان یک لیست یا یک چندتایی یا ... را از حالت بسته‌بندی خارج کرد.
</div>

In [29]:
print(*[1, 2, 3]) # 1 2 3

print(*(1, 2, 3)) # 1 2 3

print(*{'a': 1, 'b': 2, 'c': 3}) # a b c


1 2 3
1 2 3
a b c


<div style = "direction:rtl">
    استفاده از کاراکتر * می‌توان مقادیر یک لیست را با فاصله در یک خط چاپ کرد. همین‌طور با توجه به خط پنجم اگر از * برای باز کردن لغت‌نامه استفاده کنیم، کلیدهای آن در نظر گرفته می‌شود. اگر بخواهیم یک لغت‌نامه را به صورت kwargs به یک تابع بدهیم کافی است از کاراکتر ** به جای * استفاده کنیم. به مثال‌های زیر توجه کنید:
</div>

<div style = "direction:rtl">
    <b> مثال 1</b> <br>
فرض کنید تابعی به‌نام mean وجود دارد که به تعداد دلخواه ورودی گرفته و میانگین آن‌ها را خروجی ‌می‌دهد. لیستی از اعداد وجود دارد که می‌خواهیم آن‌‌ها را به mean بدهیم. 
</div>

In [27]:
def mean(*numbers):
    return sum(numbers)/len(numbers)
    pass
data = [1, 2, 3, 4, 5]
print(mean(*data))

3.0


<div style = "direction:rtl">
    <b> مثال 2 </b> <br>
    این بار فرض کنید تابعی به‌نام people وجود دارد ورودی‌هایی از نوع kwargs گرفته و تمامی آن‌ها را با یک قالب مشخص چاپ می‌کند یک لغت‌نامه وجود دارد که می‌خواهیم مقادیر آن‌ را به people بدهیم.
</div>

In [33]:
# in this, first dict "data" sperate, then passes to function, then use it as dict "people"
def people(**people):
    for name, job in people.items():
        print(f'{name} is a {job}')
        pass
    pass
data = {'mohamad': 'engineer', 'samad': 'worker'}
people(**data)

mohamad is a engineer
samad is a worker


In [32]:
# in this, data passes in type "dict"
def people(people):
    for name, job in people.items():
        print(f'{name} is a {job}')

data = {'mohamad': 'engineer', 'samad': 'worker'}
people(data)

mohamad is a engineer
samad is a worker



#### 2.6.6. lambda functions

<div style = "direction:rtl">
گاهی اوقات می‌خواهیم یک شی ساده قابل فراخوانی برای پاس دادن به تابع بدون ایجاد سرباری که def ایجاد می‌کنند بسازیم. در این مواقع به توابع ناشناس (lambda function) نیاز پیدا می‌کنیم. توابع ناشناس توابعی کوچکی هستند که می‌توانند هر تعداد ورودی (arguments) داشته باشند ولی تنها یک عبارت (expression) را خروجی می‌دهند. البته می‌توان چندین عبارت را در قالب یک چندتایی یا لیست خروجی داد. <br>
    این توابع معمولا یکبار مصرف هستند که باعث کوتاه‌تر شدن کد می‌شوند البته باید توجه داشت که استفاده بیش‌از حد از توابع ناشناس باعث ابهام در کد می‌شود.
</div>

                                                              lambda arguments : expression


<div style = "direction:rtl">
    می‌توان بدون نام‌گذاری این توابع از آن‌ها استفاده نمود به همین خاطر به انها توابع ناشناس می گوییم. البته مانند توابع ساده خود پایتون می‌توان توابع ناشناس را درون یک متغیر ریخته که صدا زدن آن متغیر همانند صدا زدن تابع ناشناس می‌باشد. توجه داشته باشید همان‌طور که گفتیم این تابع می‌تواند چندین ورودی داشته باشد.
</div>

In [16]:
print((lambda x: x * x)(2)) # 4
power_two = lambda x: x * x
print(power_two(2)) # 4


average = lambda a, b: (a + b) / 2
print(average(20, 18)) # 19.0

statistic = lambda a, b: [(a + b) / 2, max(a, b)]
print(statistic(20, 18)) # [19.0, 20]


4
4
19.0
[19.0, 20]


<div style = "direction:rtl">
    رایج‌ترین استفاده از تابع‌های لامبدا در کدهایی است که نیازمند توابع یک‌خطی ساده‌ای هستند و نوشتن یک تابع معمولی کامل، زیاده کاری محسوب می‌شود.
</div>

In [ ]:
mylist = [(1,3),(4,5),(2,10),(9,6)]

mylist.sort()
print(mylist) # [(1, 3), (2, 10), (4, 5), (9, 6)]


mylist.sort(key = lambda x: x[-1])
print(mylist)  # [(1, 3), (4, 5), (9, 6), (2, 10)]


<div style = "direction:rtl">
    قدرت lambda زمانی بهتر نشان داده می‌شود که از آنها به عنوان توابع ناشناس در درون توابع دیگر استفاده کنید.
</div>

In [18]:
def myfunc(n):
    return lambda a : a * n

mydoubler = myfunc(2)
mytripler = myfunc(3)

print(mydoubler(11)) # 22
print(mytripler(11)) # 33

22
33


#### 2.6.7. Generators

<div style = "direction:rtl">
    یکی از پیمایش‌شونده‌هایی که به طور عادی در پایتون وجود دارند، تولیدکننده‌ها یا generators هستند. در این نوع متغیرها مانند سایر پیمایش‌شونده‌ها می‌توان به عضو بعدی و یا عضو iiام دسترسی داشت. همچنین این نوع از متغیرها حتما باید خروجی یک تابع باشند. برای این که خروجی تابع از این نوع باشد، باید به جای استفاده از return به منظور خروجی دادن، از yield استفاده‌ کرد. نحوه عملکرد این دستور به‌ این صورت است که در هر زمان مفسر به یکی از این دستورها برسد، آن را به انتهای تولیدکننده اضافه‌ می‌کند و زمانی که به انتهای تابع برسد آن را بر می‌گرداند.
    <br>
    یکی از دلایل بهتر بودن generator ها نسبت به لیست ها ، حافظه خیلی کمی است که generator ها اشغال می کنند.
</div>

In [23]:
def f(n):
    yield n//1
    yield n//2
    yield n//3

div = f(6)
print(type(div))
print(div)
print(list(div))

<class 'generator'>
<generator object f at 0x000001F9C25F03C0>
[6, 3, 2]


<div style = "direction:rtl">
    ابتدا تابع f یک عدد ورودی گرفته و به ترتیب خارج قسمت آن را بر ۱ و ۲ و ۳ را بر می‌گرداند. همان طور که مشخص است نوع خروجی تابع ما generator می‌باشد.در خط سوم هم div به list تبدیل شده که همان خروجی مورد نظر ما را داده‌ است.
<br>
با استفاده از تابع زیر هم می‌توانیم range را با استفاده از generator پیاده‌سازی کنیم.
</div>

In [22]:
def myRange(l, r, step=1):
    while l < r:
        yield l
        l += step
    return 0
    yield 0
    pass
for i in myRange(1, 10, 3):
    print(i, end=' ')
    pass
print()
print(list(myRange(1, 20, 4)))

1 4 7 
[1, 5, 9, 13, 17]


<div style = "direction:rtl">
دقت کنید که دستور yield 0 به این دلیل که قبل از آن یک return آمده است، هیچوقت اجرا نمی‌شود.
</div>

---------------------------
### 2.7. Decorators

#### 2.7.1. Basics

<div style = "direction:rtl">
به طور کلی decorator تابعی است که یک تابع ورودی گرفته و تابعی جدید بر اساس تابع ورودی می‌سازد (که در بین صدا شدن این تابع و تابع اصلی یک سری مدیریت‌ها و آماده سازی‌ها صورت می‌گیرد) و تابع ساخته شده را خروجی می‌دهد
</div>

<div style = "direction:rtl">
برای مثال یک decorator تعریف می‌کنیم که چک می‌کند ورودی تابع حتما از جنس int باشد.
</div>

In [1]:
def int_check_decorator(f):
    def g(x):   # "x" is argument of function "f"
        if type(x) != int:
            raise Exception('argument should be int')
        return f(x)
    return g

def f(a):
    return a+a

print(f('salam'))

f = int_check_decorator(f)
print(f('salam'))

salamsalam


Exception: argument should be int

<div style = "direction:rtl">
در پایتون معمولا decorator با استفاده از @ خوانده می‌شود. به این شکل که بعد از @ اسم decorator می‌آید و در خط بعد تابع مورد نظر تعریف می‌شود. پایتون تابع را به decorator ورودی می‌دهد و جای آن خروجی decorator را می‌گذارد.
    <br>
    معادل مثال قبل به شکل زیر است.
</div>

In [4]:
def int_check_decorator(f):
    def g(x):
        if type(x) != int:
            raise Exception('argument should be int')
        return f(x)
    return g

@int_check_decorator
def f(a):
    return a+a

print(f('salam'))

Exception: argument should be int

<div style = "direction:rtl">
مثال دیگر:
</div>

In [3]:
def return_value_for_10(f):
    return f(10)

@return_value_for_10
def f(a):
    return a+a

print(f)

20


<div style = "direction:rtl">
پایتون تابع بعد decorator را به return_value_for_10 ورودی می‌دهد. این decorator مقدار تابع را برای ورودی 10 حساب کرده و جای f این مقدار را می‌گذارد. پس خروجی کد باید عدد ۲۰ باشد.
</div>

#### 2.7.2. Applications of Decorators 

<div style = "direction:rtl">
<h5> 2.7.2.1. کنترل آرگومان‌ها </h5> 
<br>
همان طور که در مثال اول دیدید با استفاده از decorator می‌توان کنترل کرد که آرگومان‌های تابع به چه شکل باشند.
</div>

<div style = "direction:rtl">
<h5> 2.7.2.2. شمردن تعداد دفعات صدا شدن تابع </h5>
    <br>
    یک decorator تعریف می‌کنیم که یک لغت‌نامه از اسم توابع و تعداد دفعات صدا شدن آنها درست ‌می‌کند.
</div>

In [7]:
calls = {}

def call_count_decorator(func):

    calls[func.__name__] = 0

    def ret(*args, **kwargs):
        calls[func.__name__] += 1
        return func(*args, **kwargs)

    return ret

@call_count_decorator
def f(x):
    pass

@call_count_decorator
def g(x, y):
    pass

@call_count_decorator
def h():
    pass

f(1)
f('a')
f('salam')
g(1, 2)
g(2, 2)
h()
h()
for k, v in calls.items():
    print(k + ": " + str(v))


f: 3
g: 2
h: 2


<div style = "direction:rtl">
@call_count_decorator روی جایی که تابع داره تعریف میشه، مثلا تابع f(x) معادل دستور زیره. البته بعد از اینکه تابع f رو تعریف کرده باشین.
<br>
f = call_count_decorator(f)
<br>
دستور بالا باعث میشه تابع call_count_decorator با ورودی تابع f صدا زده بشه (به یاد بیارین همه چیز در پایتون یه شی هست حتی توابع) خروجی تابع call_count_decorator تابع ret هست. پس مقدار تابع ret داخل f قرار میگیره. منتهی تابع ret که برای f شخصی سازی شده. پس از این به بعد هر بار که f صدا زده بشه، ret صدا زده میشه.
    <br>
    پس به طور کلی عبارت هایی که خارج تابع داخل decorator نوشته می شوند ، به ازای هر بار نوشتن @decorator_name   تنها یکبار اجرا می شوند ، نه اینکه به ازای هر بار صدا شدن تابع ورودی decorator انها نیز اجرا شوند.
</div>

<div style = "direction:rtl">
با استفاده از (*args, **kwargs) می‌توان به هر شکل ورودی گرفت.
<br>
در obj.__name__ نام آن شی نگه‌داری می‌شود.
</div>

<div style = "direction:rtl">
<h4> 2.7.3. ورودی دادن به decorator </h4>
    <br>
    همان طور که اشاره شده برای استفاده از decorator باید آن را بعد از @ نوشت. خود چیزی که بعد از @ نوشته می‌شود هم می‌تواند خروجی یک تابع دیگر(!) باشد. به این روش می‌توان decoratorهایی ساخت که آرگومان ورودی می‌گیرند.
<br>
برای مثال تابع زیر یک decorator تولید می‌کند که با توجه به پارامتر‌های تابع سازنده تشکیل می‌شود.
</div>

In [8]:
def decorator_builder(check_class):  # "check_class" is the input of decorator
    def type_checker(func):  # "func" is the function that decorator is used for
        def ret(x):  # "x" is the input of "func".
            if not isinstance(x, check_class):
                return "Argument must be " + check_class.__name__
            else:
                return func(x)
        return ret
    return type_checker

@decorator_builder(int)
def f(x):
    return 2**x

@decorator_builder(type("salam"))
def g(x):
    return x + " khoobi?"

print('f:')
print(f('salam'))
print(f(1))

print('g:')
print(g('salam'))
print(g(1))

#در واقع استفاده از این دکوراتور بدون @ مطابق زیر است
print("form2:")
decorator = decorator_builder(int)
f = decorator(f)
print(f("salam"))
print("form3:")
#و یا به شکل زیر
print(decorator_builder(int)(f)("salam"))

f:
Argument must be int
2
g:
salam khoobi?
Argument must be str
form2:
Argument must be int
form3:
Argument must be int


<div style = "direction:rtl">
خروجی تابع decorator_builder یک decorator است که جنس آرگومان ورودی تابع را کنترل می‌کند. وقتی بعد از @ این تابع استفاده می‌شود این تابع براساس ورودی داده‌شده decorator مورد نظر را می‌سازد و خروجی می‌دهد و انگار آن را جلوی @ نوشته‌ایم.
</div>

<div style = "direction:rtl">
<h4> 2.7.4. کلاس‌ها به عنوان decorator </h4>
<br>
کلاس و یا هر شی صدا شونده‌ای می‌تواند یک decorator باشد.
</div>

In [9]:
class decorator:

    def __init__(self, msg):
        self.msg = msg

    def __call__(self, func):
        def ret():
            print(self.msg)
            return func()
        return ret

dec = decorator('salam')

@dec
def f():
    pass

@decorator('hello')
def g():
    pass

f()
g()


salam
hello


---------------------------------
### 2.8. Data Structure

#### 2.8.1. Lists

list is a data structure that keeps a list of any type of objects. <br>
- list is a mutable object. <br>
- list is a iterable.

In [31]:
lucky_numbers = [4, 8, "fifteen", 16, 23, 42.0]  # for making a list, use []

zeros = [0]*100  # makes a list of lenght 100 with all zero.

salamlist = list("salam") # list() function is used for convertion to list
ls = list((20, 30, 40))


lucky_numbersC = lucky_numbers[:]    # copying a list

- List passes by-reference.

In [34]:
### list Indexing
print(lucky_numbers[1])  
print(lucky_numbers[-1])   #  = lucky_numbers[len(lucky_numbers) - 1]
print(lucky_numbers[2:])  
print(lucky_numbers[2:4])
print(lucky_numbers[:])

### changing of list
lucky_numbers[0] = 90
print(lucky_numbers[0])
lucky_numbers[2:5] = ["eighteen", 12.5, 1]
print(lucky_numbers[2:5])


print(len(lucky_numbers))  


x = range(0, 10, 1)  # "range(start, end, step)" is a function which creates a integer list from "start" to "end" (except end) with step of "step"
print(x[1])

8
42.0
['fifteen', 16, 23, 42.0]
['fifteen', 16]
[4, 8, 'fifteen', 16, 23, 42.0]
90
['eighteen', 12.5, 1]
6
1


##### 2.8.1.1. List Functions (Very Important!)

- by "del" and "append()", we can construct a stack or a queue.  

In [8]:
z = 4
friends = []
friends.extend(["Oscar"])  # .extend(iterable)    insert iterable at the end of the list
friends.extend([z, "1, 5"])
friends.extend(["Angela"])
friends.insert(1, "KevinSmith") # inserts the value in the place with index 1
print( friends ) 

print( friends.index("Oscar") )  # list.index(x, startIndex, endIndex)
print( friends.count("Angela") )

friends.remove(4) # .remove(value) remove element with the value
del friends[0]  # remove value of index 0


# list.sort(key=None, reverse=False) - key and reverse are optional - all values of list must have same type
friends.sort()  
print(friends)
def getLength(a):
    return len(a)
    pass
friends.sort(key=getLength) # sorts based on lenght
print(friends)
friends.sort(reverse=True) 
print(friends)

wholestr = '/'.join(friends) # concatenate all values of friends list with / and returns a string. all values of list must be string
print(wholestr)

['Oscar', 'KevinSmith', 4, '1, 5', 'Angela']
0
1
['1, 5', 'Angela', 'KevinSmith']
['1, 5', 'Angela', 'KevinSmith']
['KevinSmith', 'Angela', '1, 5']
KevinSmith/Angela/1, 5


--------------------------------
- __"del" instruction__

<div style = "direction:rtl">
یکی از کاربرد های دستور del حذف عضو از لیست است. تفاوت این دستور با تابع list.pop() در این است که می‌توان با این دستور بخشی از یک لیست را حذف کرد.
</div>

In [8]:
a = ['ali', 'rafte', 'key', 'barmigarde?']
del a[0]
print(a) # ['rafte', 'key', 'barmigarde?']

del a[0:2]
print(a) # ['barmigarde?']

del a[:]
print(a) # []

['rafte', 'key', 'barmigarde?']
['barmigarde?']
[]


<div style = "direction:rtl">
    دستور del، می‌تواند متغیرها، توابع و کلاس‌های ساخته‌شده و ... را نیز به طور کلی حذف کند
</div>

In [9]:
name = "salam"
print(name)
del name
print(name)

salam


NameError: name 'name' is not defined

------------------------------

##### 2.8.1.2. list Iteration

In [34]:
myList = ['ali', 1, 2, 3, 'chetor']
for it in myList:
    print(it)
    pass

ali
1
2
3
chetor


###### 2.8.1.2.1. "enumerate" function

<div style = "direction:rtl">
    با این تابع می‌توان اندیس یک شیء که پیمایش می‌شود را نیز هم‌زمان با خود شیء در دسترس داشت.
</div>

In [36]:
myList = [0, 1, 2, 3]
for i, it in enumerate(myList):
    print("the {0}th object in myList is {1}!".format(i+1, it))
    pass

the 1th object in myList is 0!
the 2th object in myList is 1!
the 3th object in myList is 2!
the 4th object in myList is 3!


###### 2.8.1.2.2. "zip" function

<div style = "direction:rtl">
با استفاده از این تابع می‌توان چند لیست را به طور هم‌زمان پیمود.
</div>

In [37]:
listA = [1, 2, 3, 4]
listB = ['a', 'b', 'c', 'd']
listC = ['I', 'II', 'III', 'IV']
for a, b, c in zip(listA, listB, listC):
    print("{0}th alphabet or {1} in greece is {2}".format(a, c, b))
    pass

1th alphabet or I in greece is a
2th alphabet or II in greece is b
3th alphabet or III in greece is c
4th alphabet or IV in greece is d


###### 2.8.1.2.3. "filter" function

<div style = "direction:rtl">
این تابع به عنوان آرگومان به ترتیب یک تابع (فرض کنید f) و یک شیء قابل پیمایش (فرض کنید iter) را می‌گیرد. تابع f را برای همه‌ی عناصر شیء iter صدا می‌زند. اگر خروجی False بود آن عنصر را حذف می‌کند. نهایتا نتیجه را در قالب یک پیمایشگر بر‌می‌گرداند.
</div>

In [ ]:
def f(x):
    return True if x%2 == 0 else False
    pass

ls = [1, 2, 4, 3, 6, 4]
print(filter(f, ls))
for x in filter(f, ls):
    print(x, end=' ')
    pass

###### 2.8.1.2.4. "map" function

<div style = "direction:rtl">
    ساختار این تابع همانند filter است ولی عملکرد آن‌ها با هم متفاوت است. به این صورت که تابع f را برای همه‌ی عناصر شیء iter صدا می‌زند و خروجی آن را جایگزین عنصر کنونی iter می‌کند. نهایتا نتیجه را در قالب یک پیمایشگر بر‌می‌گرداند.
</div>

In [ ]:
def f(x):
    return int(x)

ls = [2, '4', False, 3.14]
print(map(f, ls))
for x in map(f, ls):
    print(x, end=' ')
    pass
for x in map(int, ls):
    print(x, end=' ')
    pass

<div style = "direction:rtl">
    در مثال بالا int را به عنوان آرگومان به map دادیم. ولی آن‌ را از قبل تعریف نکرده‌ بودیم. ولی همان‌طور که در درس‌های گذشته دیدیم، int یک ورودی می‌گیرد و آن را به عدد صحیح تبدیل می‌کند. در نتیجه می‌توان با استفاده از یک خط در یک خط به تعداد دلخواه ورودی گرفته و آن‌ها را با استفاده از تابع map به روش‌های گوناگونی تغییر داد. فرض کنید می‌خواهید در یک خط تعداد نامشخصی عدد را از کاربر دریافت کرده و جمع آن‌ها را بدست آورید :
</div>

In [ ]:
number = map(int, input().split())
print(number)

print(sum(number))

###### 2.8.1.2.5. "sum" function

<div style = "direction:rtl">
    با استفاده از تابع sum می‌توان حاصل جمع مقادیر درون یک شیء قابل پیمایش را بدست آورد. دقت کنید که مقادیر درون شیء موردنظر باید حتما از نوع عددی باشند. به مثال زیر دقت کنید :
</div>

In [ ]:
ls = [1, 2, 3, 4]
print(sum(ls))

In [39]:
ls = ['a', 'b', 'c', 'd']
sum(ls)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

##### 2.8.1.3. list comprehension

In [10]:
sq = [x*x for x in range(10)]
print(sq)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


<div style = "direction:rtl">
    یک معرف‌ لیست، شامل یک [] می‌باشد که در آن عبارتی نوشته شده است و به دنبال آن for می‌آید. پس از عبارت for می‌تواند تعدادی دستور کنترلی بیاید. در نهایت لیست بر اساس عبارت اول ساخته می‌شود.
</div>

In [ ]:
print([0 for x in range(5)])

In [ ]:
print([str(x)+y for x in [1, 2, 3] for y in ['A', 'B']])
['1A', '1B', '2A', '2B', '3A', '3B']

In [ ]:
print([(x, y) for x in [1, 2, 3] for y in [1, 2, 3] if x != y])

In [13]:
data = [10, -4, 53, 122, 0]
print([x for x in data if x > 0])
print([x*x for x in data])

[10, 53, 122]
[100, 16, 2809, 14884, 0]


In [12]:
print([x*x, x for x in data])

SyntaxError: invalid syntax (Temp/ipykernel_21624/225557189.py, line 1)

<div style = "direction:rtl">
    دقت کنید که فقط می‌توانید یک عبارت قبل اولین ‍‍for بنویسید تا لیست از روی آن ساخته شود، برای همین آخرین دستور در مثال بالا خطای نحوی می‌دهد.
</div>

##### 2.8.1.4. nested list

<div style = "direction:rtl">
    همانطور که گفته شد لیست می‌تواند شامل شی‌هایی از هر جنس باشد. به طور خاص می‌توان لیستی از لیست‌ها ساخت. این یک روش به‌صرفه برای پیاده‌سازی آرایه‌های چندبعدی‌ است.
</div>

In [5]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
for i in range(3):
    for j in range(3):
        print(matrix[i][j], end=' ')
        pass
    print()
    pass

1 2 3 
4 5 6 
7 8 9 


<div style = "direction:rtl">
    حال فرض کنید می‌خواهید یک لیست دارای nn سطر و mm ستون بسازید که هرکدام از خانه‌های آن صفر باشد. چنین چیزی را به چند روش می‌توان انجام داد که دو روش از آن‌ها در زیر آمده‌اند. در روش اول از عملگر * و در روش دوم از معرف لیست استفاده شده است.
</div>

In [ ]:
zeros = [[0]*m]*n    # first way

In [ ]:
zeros = [[0 for c in range(m)] for r in range(n)]    # second way

----------------------
#### 2.8.2. Tuple

is a data structure that keeps some objects of any type (like list).
- Tuple is immutable(difference between list and tuple).
- Tuple is a iterable.

In [2]:
# definition of tuple
t = ("ali", 123, 2.5)
print(t)
print(type (t))

t = tuple([2, 4])
print(t)

('ali', 123, 2.5)
<class 'tuple'>
(2, 4)


In [3]:
t = ()
print(len(t)) # 0
print(type(t)) # class 'tuple'


t = (1)
print(type(t)) # class 'int'


t = 1,
print(len(t))  # 1
print(type(t)) # class 'tuple'


0
<class 'tuple'>
<class 'int'>
1
<class 'tuple'>


In [5]:
a, b, c = 10, 20, 30
print(a) # 10
print(b) # 20
print(c) # 30


a, b = b, a
print(a) # 20
print(b) #10

10
20
30
20
10


In [6]:
# tuple indexing is like list, etc. 
t = ("ali", 123, 2.5)
print(t[0])
print(t[0:2])

for it in t:
    print(it)
    pass

ali
('ali', 123)
ali
123
2.5


- one of applications of tuple is returning several value from function, because of being immutable, it is better to use tuple instead of list.

In [8]:
# returning by list
myList = [1, 2]
def f():
    return myList
    pass
a = f()
a.append("12")
print(myList) # [1, 2, '12']
a[0] = 10
print(myList) # [10, 2, '12']

[1, 2, '12']
[10, 2, '12']


In [9]:
# returning by tuple
myTuple = (1, 2)
def f():
    return myTuple
a = f()
print(a) # (1, 2)
a[0] = 10 # because tuple is immutable

(1, 2)


TypeError: 'tuple' object does not support item assignment

In [10]:
a = 3, 4
print(myTuple)

(1, 2)


---------------------------
#### 2.8.3. Set

Set in pyhton is like set in math.
- mutable
- Set don't have order and repeatance (difference between list and set)

In [12]:
print(type(set())) # <class 'set'>

st = {2, 3, 1}
print(st) # {1, 2, 3}
print(len(st)) # 3
print(type(st)) # <class 'set'>

st = {}   # for creating null set, we must use set() 
print(type(st)) # <class 'dict'>

<class 'set'>
{1, 2, 3}
3
<class 'set'>
<class 'dict'>


In [13]:
# adding to Set
names = set()
names.add('ali')
names.add('mohamadreza')
names.add('amir')
names.add('amir') # if a value exists in the set, it won't be added again.
print(names)

{'ali', 'mohamadreza', 'amir'}


##### 2.8.3.1. removing a value from set

Set doesn't have order, so we cannot remove from the list by index.

In [18]:
a = {1, 2, 3}
a.remove(1)
a.discard(2)
print(a)

{3}


- difference between remove() and discard () is that if the value don't exist in the set, discard(the value) do not err but remove(the value) err.

In [15]:
a.discard(4) 

In [16]:
a.remove(4)

KeyError: 4

In [19]:
a = {1, 2, 3}
b = {3, 2, 4}
print(a.intersection(b)) # اشتراک دو مجموعه
print(b.intersection(a))

print(b.union(a)) # اجتماع دو مجموعه

{2, 3}
{2, 3}
{1, 2, 3, 4}


In [21]:
a = {1, 2, 3}
b = {3, 2, 4}
print(a.difference(b)) # {1}     # تفاضل دو مجموعه

print(b.symmetric_difference(a)) # {1, 4}    # تفاضل متقارن دو مجموعه

{1}
{1, 4}


In [14]:
# Set Comprehension
a = set("salam")
b = set("varam")
print({x for x in a if x not in b})   # like list comprehension

{'s', 'l'}


-------------------------
#### 2.8.4. Dict

<div style = "direction:rtl">
    یک داده‌ساختار تغییر‌پذیر در پایتون است. لغت‌نامه را می‌توان لیستی تعریف کرد که اندیس‌های آن به جای این که عدد باشند، اشیای تغییر‌ناپذیر هستند. مانند رشته‌ها، اعداد و چندتایی‌هایی که شامل اشیای تغییرپذیر نمی‌شوند. لغت‌نامه از جفت‌هایی تشکیل شده‌ است. هرکدام از این جفت‌ها دارای یک کلید (key) و مقدار (value) می‌باشند. کلیدها نمی‌توانند تکراری باشند و هر کلید مقدار خاص و یکتایی دارد. می‌توان به مقدار هر کلید با داشتن آن، دسترسی پیدا کرد و آن را تغییر داد. دقت کنید که کلیدها تغییرناپذیر هستند.
</div>

In [12]:
dict = {"ali": 12, "amir": 2.3}  # { key:value }

print(dict)

print(dict['ali']) # indexing in dict : dict[key] 

dict['ali'] = 23
print(dict)

print(list(dict))  # returns list of keys

{'ali': 12, 'amir': 2.3}
12
{'ali': 23, 'amir': 2.3}
['ali', 'amir']


In [16]:
# changing and adding to dict
age = {'mohamadreza':17} 
age['ali'] = 22               # adding to dict, because the key ('ali') do not exist in the dict.
age['mohamadreza'] = 18      # changing in dict, because the key ('mohamadreza') exists in dict.
print(age)

{'mohamadreza': 18, 'ali': 22}


In [10]:
# access and finding a key in the dict

square = {1: 1, 2: 4, 3: 9, 4: 16}
print(3 in square)    # key in dictname
print(square[3])

True
9


In [11]:
print(5 in square)
print(square[5])

False


KeyError: 5

In [8]:
square = {1: 1, 2: 4, 3: 9, 4: 16}

print(square.pop(3))

del square[1]  # difference between pop() and del is that pop() returns value of removed key.

print(square)

9
{2: 4, 4: 16}


In [9]:
square.pop(5) # if the mentioned key do not exist, we see error ( KeyError )

KeyError: 5

In [7]:
# dict.get(key, x)  if key do not exists, returns x 

grade = {'mamad': 20, 'ali':19, 'pooyan':19}
print(grade.get('ali'))

grade['mahdi'] = grade.get('mahdi', 19) + 1 
print(grade.get('mahdi'))

19
20


In [6]:
# .values() and .keys() return an iterable.
age = {'ali': 21, 'mmdreza': 18, 'mahdi': 22, 'pooyan':25}

print(type(age.values()) )
print(type(age.keys()))

print(age.values())
print(list(age.values()))

<class 'dict_values'>
<class 'dict_keys'>
dict_values([21, 18, 22, 25])
[21, 18, 22, 25]


##### 2.8.4.1. dict comprehension

In [5]:
dic = {x:x*x for x in range(5)}
print(dic)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}


##### 2.8.4.2. dict iteration

In [4]:
d = {'ali': 'A', 'amir': 'B'}
for k, v in d.items():
    print(k + " got " + v) 
    pass

ali got A
amir got B


-----------------------------------
- __"len" function__

In [1]:
print(len("Salam"))    # len string  # counts characters of string
print(len([1, 2, 3]))  # len list  # counts elements of list
print(len({'ali': 'A', 'amir': 'B'})) # len dict   # counts keys of dict
print(len(()))  # len tuple # counts element of tuple

5
3
2
0


"len" function is an example for polymorphism. "len" function calculates length of objects with different types.

------------------------------------
### 2.9. ERRORS in Python

#### 2.9.1. Syntax Error : Interpreter cannot find out the instruction.

In [4]:
while True print('Hello World!') 

SyntaxError: invalid syntax (Temp/ipykernel_15616/2651466651.py, line 1)

- Identation Error : This error occurs when scoping is not correct.

In [5]:
print("salam")    # first line also do not excute, because first, interpreter checks syntax of whole program, Then starts excuting.
    x = 2
print(x)

IndentationError: unexpected indent (Temp/ipykernel_15616/2099578784.py, line 2)

#### 2.9.2. Runtime Errors : When program runs, these errors show up. In python, called  __Exceptions__

In [9]:
x = 1/0

ZeroDivisionError: division by zero

In [10]:
print(y)

NameError: name 'y' is not defined

In [11]:
z = int('salam')

ValueError: invalid literal for int() with base 10: 'salam'

<div style = "direction:rtl">
    به طور کلی ساختار خروجی استثناها توسط Interpreter به این ترتیب است که ابتدا مشخص می‌کند که در کدام بخش برنامه این خطا رخ‌ داده و stack traceback برنامه در آن زمان به چه شکل بوده‌است. در خط آخر نیز نوع استثنا به همراه یک توضیح کوتاه بعنوان دلیل رخ‌دادن خطا نمایش داده خواهد شد.
</div>

##### 2.9.2.1. Exceptions Managment

<div style = "direction:rtl">
    فرض کنید، می‌خواهیم کاری کنیم تا جلوی خطا دادن برنامه‌ را گرفته و خودمان خطا را مدیریت کنیم و حتی از این که بخشی از برنامه خطا می‌دهد استفاده کنیم تا کدی تمیزتر و با پیاده سازی راحت‌تر بنویسیم
</div>

In [16]:
try:
    x = int(input())
    print("It's a number!")
except Exception:
    print("It's just a string!")

 Quera


It's just a string!


<div style = "direction:rtl">
    شیوه کار دستور try به این صورت است که پس از نوشتن آن، در Scope بعد از آن دستوراتی که می خواهیم انجام شوند را می‌نویسیم. حال اگر در هنگام اجرای یکی از دستورات موجود در این محدوده، استثنایی رخ دهد برنامه از محدوده فعلی خارج شده و دستورات Scope ای که بعد از نوشتن except وجود دارد، اجرا می‌شود.
    <br>
    برای مثال در کد بالا ابتدا سعی می‌‌شود مقدار ورودی به int تبدیل شود. اگر استثنایی رخ ندهد در آن صورت عبارت It's a number! چاپ می شود؛ در غیر این صورت به Scope بعد از except رفته و عبارت It's just a string! چاپ می‌شود.
</div>

<div style = "direction:rtl">
استثناها مانند مفاهیم دیگر پایتونی یک شئ هستند و می‌توانند انواع مختلفی داشته باشند.
</div>

<div style = "direction:rtl">
در مثال بالا خطای ValueError() رخ می‌دهد، که تابع int() آن را صدا کرده‌ است (چون ما به عنوان ورودی، رشته‌ی Quera را به تابع int دادیم و این تابع قابلیت تبدیل یک رشته به یک عدد را ندارد پس این خطا پرتاب شد). این قابلیت پایتون توانایی مدیریت متفاوت انواع خطاها را به ما می دهد.
</div>

<div style = "direction:rtl">
ک دستور try می‌تواند چندین except داشته باشد و استثنا‌های مختلفی را مدیریت کند. برای این کار نوع استثنا مقابل except نوشته می‌شود.
</div>

<div style = "direction:rtl">
در ساختار try و except، ابتدا درون بخش try اجرا شده و اگر خطایی رخ دهد مفسر به exceptها توجه می‌کند؛ اگر در یکی از except‍ها خطایی از همان کلاس خطای رخ داده شده (و یا کلاسی که خطای رخ داده شده از آن ارث برده باشد) پیش‌بینی شده باشد، بخش درون آن except اجرا می‌شود. اگر چند except با این خاصیت وجود داشت؛ مفسر اولین (بالاترین از لحاظ متنی) except را انتخاب و بخش درون آن را اجرا می‌کند.
</div>

<div style = "direction:rtl">
مدیریت‌کننده‌ی (except)ها فقط می‌توانند استثنا‌هایی که در محدوده try رخ می‌دهد را مدیریت کنند و نمی‌توانند به استثنا‌های درون محدوده همدیگر دسترسی داشته باشند.
<br>
اگر جلوی هیچ exceptای خطای رخ داده شده پیش‌بینی نشده باشد unhandled exception رخ می‌دهد و اجرای برنامه متوقف می‌شود.
</div>

In [15]:
for i in range(3):
    try:
        if i == 0:
            1/0
        if i == 1:
            int("salam")
        if i == 2:
            "salam" + 1
    except ZeroDivisionError:
        print("ZeroDivisionError called") # 1/0
    except TypeError:
        print("TypeError called") # "salam" + 1
    except ValueError:
        print("ValueError called") # int("salam")

ZeroDivisionError called
ValueError called
TypeError called


<div style = "direction:rtl">
همچنین اگر جلو except ،  Exception را بنویسیم تمام استثنا ها را مدیریت می کند.
</div>

In [17]:
try:
    ...
except Exception:
    ...

<div style = "direction:rtl">
نکته : کلاس Exception والد تمام استثناها است؛ یعنی تمام استثنا‌ها به طور مستقیم یا غیرمستقیم از این کلاس ارث برده‌اند.
</div>

<div style = "direction:rtl">
یک دستور except می‌تواند چند نوع مختلف از خطا‌ها را مدیریت کند. نوع این خطاها درون پرانتز به شکل یک چندتایی (tuple) جلوی‌ دستور داده می‌شود. برای مثال:
</div>

In [18]:
for i in range(3):
    try:
            if i == 0:
                    1/0
            if i == 1:
                    int("salam")
            if i == 2:
                    "salam" + 1
    except (ZeroDivisionError, TypeError, ValueError):
            print("an error occurred")

an error occurred
an error occurred
an error occurred


<div style = "direction:rtl">
    <h5> پرتاب کردن استثنا </h5>
</div>

<div style = "direction:rtl">
با دستور raise می‌توان یک استثنا را پرتاب کرد (یعنی کاری کنیم که یک استثنایی که خودمان می‌خواهیم داده شود).
</div>

<div style = "direction:rtl">
بعد از دستور raise باید یک شی از کلاس Exception یا یک کلاس Exception ( یا کلاسی که از Exception ارث برده است) بیاید. اگر یک کلاس به دستور raise داده شود یک شی با سازنده بدون آرگومان ساخته و آن را صدا می‌کند.
</div>

In [20]:
raise ValueError() 

ValueError: 

In [19]:
raise NameError('salam')

NameError: salam

<div style = "direction:rtl">
اگر بخواهیم استثنای صدا زده شده را مدیریت کنیم و دوباره آن را صدا کنیم؛ می‌توانیم یک دستور raise خالی بنویسیم تا خطای مدیریت شده را دوباره صدا کند.
</div>

In [21]:
try:
    raise NameError('salam')
except NameError:
    print('an exception raised')
    raise 

an exception raised


NameError: salam

<div style = "direction:rtl">
همان‌طور که می‌بینید در محدوده except NameError فقط کلمه raise آمده است. چنین چیزی همان کاری را می‌کند که raise NameError انجام می‌دهد.
</div>

<div style = "direction:rtl">
    <h6> 2.9.2.1.1. تعریف کردن استثنا </h6>
</div>

<div style = "direction:rtl">
برای تعریف استثناهای‌ خود می‌توانیم یک کلاس تعریف کنیم که مستقیم یا غیرمستقیم از کلاس Exception ارث ببرد.
<br>
کلاس‌های استثنا می‌توانند مانند بقیه کلاس‌ها خصوصیات مختلفی داشته باشند ولی معمولا ساده تعریف می‌شوند و فقط خصوصیات کاربردی در مدیریت را در خود نگه‌ می‌دارند.
</div>

In [22]:
class A(Exception):
    pass
class B(A):
    pass 
class C(B):
    pass
try:
    raise C
except A as e:
    print('exception found', type(e))

exception found <class '__main__.C'>


<div style = "direction:rtl">
در کد بالا کلاس C به صورت غیرمستقیم از کلاس ‍A ارث بری می‌کند در نتیجه یک کلاس استثنا است.
با استفاده از کلیدواژه raise می‌توان یک استثنا را پرتاب کرد.
می‌توان بعد از except کلیدواژه as و سپس نام یک متغیر را نوشت و در آن صورت آن استثنا درون متغیر ریخته می‌شود که می‌توان در محدوده except از آن استفاده کرد.
</div>

<div style = "direction:rtl">
<h6> 2.9.2.1.2. استفاده از کلید واژه else </h6>
</div>

<div style = "direction:rtl">
با استفاده از عبارت else، می‌توان محدوده‌ای را مشخص کرد که در صورت عدم بروز استثنا، اجرا شود. ‍‍‍
</div>

<div style = "direction:rtl">
قطعه کد بالا یک تست را اجرا می‌کند و در صورتی که تست با شکست مواجه شود (استثنا رخ دهد)؛ به تعداد تست های ناموفق یک واحد اضافه می‌شود و پیام شکست چاپ می‌شود و در صورت پاس شدن تست‌ها به تعداد تست های موفق یک واحد اضافه می‌شود و پیام موفقیت چاپ می‌شود.
</div>

<div style = "direction:rtl">
<h6> 2.9.2.1.3. استفاده از کلید واژه finally </h6>
</div>

<div style = "direction:rtl">
دستوراتی که در محدوده بعد از finally نوشته می‌شوند، در هر شرایطی که برای محدوده try رخ دهد اجرا می‌شوند.
</div>

In [26]:
try:
    1/0
except:
    print('error!!')
    raise
finally:
    print('finally is running')

error!!
finally is running


ZeroDivisionError: division by zero

<div style = "direction:rtl">
همان‌طور که می‌بینید با اینکه یک استثنا رخ داد و مدیریت نشد باز محدوده finally اجرا شد.
با وجود اینکه تابع در محدوده try مقداری برمی‌گرداند و مفسر از تابع خارج می‌شود؛ محدوده finally اجرا می‌شود.
</div>

<div style = "direction:rtl">
    <b> عکس زیر ساختار کلی یک مدیریت خطا در پایتون است. </b>
    <br>
    <img src = "https://files.realpython.com/media/try_except_else_finally.a7fac6c36c55.png" height = 500px width = 800px >
</div>

---------------------
### 2.10. OOP

#### 2.10.1. class Definition

In [1]:
class Game():
    pass


game = Game()  # Instantiation of class game
print(type(game))
print(type(Game))

<class '__main__.Game'>
<class 'type'>


<div style = "direction:rtl">
    در این مثال ابتدا یک کلاس به نام Game تعریف کرده‌ایم و سپس یک شئ از آن جنس ساخته‌ایم و سپس نوع شئ را گرفته‌ایم که از نوع Game است (__main__ به این معناست که این کلاس در همین فایل تعریف شده‌ است).
</div>
- all classes inherit from class 'object' as default.

##### 2.10.1.1. Attribute

In [30]:
class Person():
    def __init__ (self, name, age):
        self.name = name
        self.age = age
        pass
    pass 

p1 = Person('mohamadreza', 18)
print(p1.name)
print(p1.age)

mohamadreza
18


##### 2.10.1.2. Method

<div style = "direction:rtl">
    می‌توان برای شئ، توابعی (methods) تعریف کرد که روی آن اعمال شوند و ویژگی‌های (properties) آن را تغییر دهند. برای این کار باید تابعی درون کلاس تعریف کرد که اولین ورودی آن self باشد. self در واقع نماینده همان شیئی است که تابع روی آن فراخوانی می‌شود. حال می‌توانیم از self به عنوان شئ استفاده کنیم و برای آن ویژگی‌های جدیدی تعریف و مقداردهی کنیم یا حتی ویژگی‌های قبلی آن را تغییر دهیم.
</div>

In [26]:
class Game():
     def set_money(self, money):
        self.money = money
        pass
     def get_money(self):
        return self.money
        
game = Game()

Game.set_money(game, 5)
print(Game.get_money(game))

game.set_money(4)
print(game.get_money())

5
4


<div style = "direction:rtl">
    همان گونه که مشاهده می‌کنید اگر تابع set_money یا get_money را روی خود شئ صدا بزنیم، نیازی نیست self را ورودی دهیم چون مقدارش برابر با خود شئ در نظر گرفته می‌شود. اما اگر آن را بر روی کلاس Game اجرا کنیم باید شئ مورد نظر را ورودی دهیم تا مفسر بفهمد که باید تابع را روی کدام شئ اجرا کند.
</div>

##### 2.10.1.3.  Constructor

<div style = "direction:rtl">
    می‌توان در هنگام ساختن یک شئ از یک کلاس، ویژگی‌های (properties) آن را مقداردهی کرد. برای این کار باید تابع __init__ کلاس را تعریف کنیم. در صورتی که این تابع را تعریف نکنیم، کلاس به طور پیش‌فرض ورودی‌ نمی‌گیرد و اشیاء آن مانند مثال قبل به طور ساده ساخته می‌شوند. این تابع مانند توابع دیگری که برای کلاس تعریف کردیم، ‍‍self را ورودی می‌گیرد. البته می‌توان ورودی‌های دیگری را نیز دریافت کرد. حتی می‌توان برای هرکدام از آن‌ها مقدار پیش‌فرضی تعیین کرد تا در صورتی که هنگام ساختن شئ جدید مقداردهی نشوند، مقدار پیش‌فرض برای آن‌ها در نظر گرفته شوند.
</div>

In [ ]:
>>> class Person():
...     def __init__(self, name, age=18):
...         self.name = name
...         self.age = age
...
>>> p1 = Person("Ali", 12)
>>> p2 = Person("Amir")
>>> p1.name
'Ali'
>>> p1.age
12
>>> p2.name
'Amir'
>>> p2.age
18

<div style = "direction:rtl">
    اگر می‌خواستیم به روش مثال پیشین عمل کنیم باید برای هر شیئی که از کلاس Person ساخته می‌شود، پس از ساخته شدن، به طور جداگانه ویژگی‌های name و age را تعریف می‌کردیم؛ اما با به‌کارگیری متد __init__ تضمین می‌شود همه اشیائی که از این کلاس ساخته می‌شوند، این دو ویژگی را دارا خواهند بود چرا که هنگام ساخته شدن (نه بعد از ساخته شدن) این دو ویژگی مقداردهی می‌شوند.
</div>

##### 2.10.1.4. Static Variable

<div style = "direction:rtl">
   متغیر ایستا متغیری است که به شئ ساخته شده ربطی ندارد و برای خود کلاس است. البته از شئ می‌توان به متغیرهای ایستا دسترسی داشت ولی نمی‌توان مقدار آن‌ها را تغییر داد. برای تعریف این نوع متغیر می‌توان در محدوده مربوط به کلاس، یک متغیر تعریف و مقداردهی کرد. سپس از کلاس موردنظر می‌توان به آن دسترسی داشت و آن را تغییر داد. اگر ویژگی‌ای از کلاس را مقداردهی کنیم که به صورت استاتیک در کلاس موردنظر وجود ندارد، آن ویژگی مقدار خواسته‌شده را می‌گیرد و به فضای نام مربوط به کلاس اضافه می‌شود.
</div>

In [3]:
class Game():
    goal_money = 3000

    def set_money(self, x):
        self.money = x
        pass

    def get_money(self):
        return self.money
    pass

print(Game.goal_money)   # = 3000

game = Game()
print(game.goal_money)   # = 3000

game.goal_money = 2000
print(game.goal_money)   # = 2000

Game.goal_money

del game.goal_money
print(game.goal_money)   # = 3000

3000
3000
2000
3000


<div style = "direction:rtl">
    ابتدا، یک شئ از کلاس می‌سازیم. در خط بعد مقدار goal_money از طریق آن شئ چاپ می‌شود، از آن‌جایی که این شئ به متغیرهای ایستا دسترسی مشاهده (read-only) دارد، مقدار ۳۰۰۰ چاپ می‌شود.
<br>
سپس در خط ۱۸، مقدار goal_money را برای آن شئ تغییر می‌دهیم اما از آن جا که شئ به متغیرهای ایستا دسترسی تغییر ندارد، یک ویژگی به خود شئ اضافه می‌شود و در خط بعد سپس مقدار آن چاپ می‌شود. برای اینکه مطمئن شویم مقدار متغیر ایستا تغییر نکرده است در خط ۲۱ مقدار آن‌ را دوباره از طریق کلاس چاپ می‌کنیم.
<br>
در دو خط بعد ویژگی goal_money را که به شئ اضافه شده بود و برابر ۲۰۰۰ بود پاک می‌کنیم. حال اگر goal_money را از طریق شئ بخوانیم برابر متغیر ایستای کلاس خواهد بود.
</div>

##### 2.10.1.5. Static Method

<div style = "direction:rtl">
    تایع ایستا تابعی است که روی کلاس تعریف می‌شود و دیگر دسترسی‌ به شی‍ئی که از آن تابع را صدا زدیم ندارد. در واقع می‌توان حتی بدون ساختن شئ از آن استفاده کرد. برای تعریف چنین تابعی قبل از تعریف تابع @staticmethod می‌نویسم، سپس شروع به نوشتن تابع می‌کنیم. @staticmethod یک annotation است.
</div>

In [28]:
class Sample():
    goal_money = 3000   

    @staticmethod 
    def increase_goal_money(value):
        Sample.goal_money += value
        pass

sample = Sample()
print(Sample.goal_money)
Sample.increase_goal_money(100)
print(sample.goal_money)

3000
3100


<div style = "direction:rtl">
    همان‌طور که دیدید تابع ایستا، self را به عنوان ورودی نمی‌گیرد. به همین علت در تابع ایستا نمی‌توان تشخیص داد این تابع توسط چه شیئی صدا زده شده است. با اجرا کردن این کد خواهید دید که خروجی زیر چاپ می‌شود و با صدا زدن تابع ایستای increase_goal_money، مقدار متغیر ایستای goal_money افزایش می‌یابد.
</div>

##### 2.10.1.6. Protected members

Python's convention to make an instance variable protected is to add a prefix _ (single underscore) to it. This effectively prevents it from being accessed unless it is from within a sub-class.

In [13]:
class Student:
    _schoolName = 'XYZ School' # protected static variable
    
    def __init__(self, name, age):
        self._name=name  # protected instance attribute
        self._age=age # protected instance attribute

In fact, this doesn't prevent instance variables from accessing or modifying the instance. You can still perform the following operations:

In [14]:
std = Student("Swati", 25)
print(std._name)
std._name = 'Dipa'
print(std._name)

Swati
Dipa


Hence, the responsible programmer would refrain from accessing and modifying instance variables prefixed with _ from outside its class.

##### 2.10.1.7. Private Members

The double underscore __ prefixed to a variable makes it private. It gives a strong suggestion not to touch it from outside the class. Any attempt to do so will result in an AttributeError:

In [18]:
class Student:
    __schoolName = 'XYZ School' # private class attribute

    def __init__(self, name, age):
        self.__name=name  # private instance attribute
        self.__salary=age # private instance attribute
    def __display(self):  # private method
        print('This is private method.')

In [19]:
std = Student("Bill", 25)

std.__schoolName

AttributeError: 'Student' object has no attribute '__schoolName'

In [20]:
std.__name

AttributeError: 'Student' object has no attribute '__name'

In [21]:
std.__display()

AttributeError: 'Student' object has no attribute '__display'

Python performs name mangling of private variables. Every member with a double underscore will be changed to _object._class__variable. So, it can still be accessed from outside the class, but the practice should be refrained.

In [22]:
std = Student("Bill", 25)
print(std._Student__name)
std._Student__name = 'Steve'
print(std._Student__name)
std._Student__display()

Bill
Steve
This is private method.


#### 2.10.2. Polymorphism in Python

In [3]:
class Account:
    def __init__(self, full_name, username, password):
        self.full_name = full_name
        self.username = username
        self.password = password
        self.courses = []   

    def add_course(self, new_course):
        self.courses.append(new_course)
        pass
    pass
class Student(Account):
    def __init__(self, full_name, username, password, rank_in_college):
        super().__init__(full_name, username, password)
        self.rank_in_college = rank_in_college

    def get_rank(self):
        return f'Student {self.full_name} rank in the college is {self.rank_in_college}!' 

class Professor(Account):
    def __init__(self, full_name, username, password, h_index_rank):
        super().__init__(full_name, username, password)
        self.h_index_rank = h_index_rank   

    def get_rank(self):
        return f'Professor {self.full_name} H-Index rank is {self.h_index_rank}!' 
    pass

ali = Student('Ali Safinal', 'safinal', '@Li2001', 13)
seyed = Professor('Seyed Ali Babaei', 'SalibeBaSalabat1234', '786ff912', 80)

In [4]:
print(ali.get_rank())

Student Ali Safinal rank in the college is 13!


In [5]:
print(seyed.get_rank())

Professor Seyed Ali Babaei H-Index rank is 80!


<div style = "direction:rtl">
    با وجود اینکه نام متد در هر دو حالت یکسان است ولی کارکرد آن برای شیء استاد کاملا متفاوت با شیء دانشجو است.
</div>

#### 2.10.3.  Inheritance in Python

<div style = "direction:rtl">
در ارث‌بری یک کلاس می‌تواند تمام ویژگی‌ها، شامل توابع و متغیرهایی که در یک کلاس دیگر تعریف شده‌اند را به خودش انتقال دهد. در این عملیات به کلاسی که ويژگی‌ها را می‌گیرد فرزند و به کلاسی که ویژگی‌ها را می‌دهد پدر می‌گویند.
</div>

In [ ]:
class Parent():
    def __init__(self, name):
        self.name = name
        pass
    pass
class Child(Parent):
    def __init__(self, name):
        self.name = name
        pass
    pass

<div style = "direction:rtl">
برای ارث‌بری در پایتون کافی‌ست در زمان تعریف کلاس فرزند، نام کلاس پدر را به عنوان ورودی به فرزند بدهیم. توجه کنید که برای این کار کلاس پدر حتما باید قبل از کلاس فرزند تعریف شده‌‌باشد. همچنین اگر برای یک کلاس پدری مشخص نکنیم، به طور پیش‌فرض object به‌عنوان پدرش در نظر گرفته می‌شود.
</div>

In [3]:
class Person():
    def __init__(self, name):
        self.name = name

##### 2.10.3.1. using of "super"

In [4]:
class Person(object):
    def __init__(self, name):
        self.name = name

<div style = "direction:rtl">
در بخش بالا دیدیم که چطور می‌توانیم از یک کلاس ارث‌بری کنیم و حالا می‌خواهیم به این بپردازیم که چطور از توابع کلاس پدر در کلاس فرزند استفاده کنیم.
</div>

<div style = "direction:rtl">
پایتون دارای تابعی به نام super می‌باشد که با استفاده از آن، در داخل کلاس فرزند می‌توان به توابع کلاس پدر دسترسی داشت و از آن‌ها استفاده کرد.
</div>

In [5]:
class Person:
    def __init__(self):
        print('Initialize from class Person')

class Engineer(Person):
    def __init__(self):
        print('Initialize from class Engineer')
        super().__init__()

eng = Engineer()

Initialize from class Engineer
Initialize from class Person


<div style = "direction:rtl">
برای مثال فرض کنید تابعی در کلاس پدر وجود دارد و ما تابعی با همان اسم در کلاس فرزند تعریف کرده‌ایم. در آن صورت با صدا زدن آن تابع، تابعی که در کلاس فرزند وجود دارد صدا می‌شود و اگر بخواهیم تابع کلاس پدر را صدا بزنیم می‌توانیم از super استفاده کنیم. برای درک این موضوع به مثال زیر دقت کنید:
</div>

In [6]:
class Person:
    def __init__(self):
        print('Initialize from class Person')

    def output(self):
        print('Output from class Person')

class Engineer(Person):
    def __init__(self):
        print('Initialize from class Engineer')

    def output(self):
        print('Output from class Engineer')
        super().output()

sepehr= Engineer()
sepehr.output()

Initialize from class Engineer
Output from class Engineer
Output from class Person


<div style = "direction:rtl">
در این مثال ما شئ‌ای از کلاس ‍‍Engineer ایجاد کرده و تابع ‍‍output را فراخوانی می‌کنیم. در هنگام ایجاد این آبجکت، تابع __init__ مربوط به کلاس ‍‍Engineer صدا زده می‌شود و هنگام فراخوانی تابع output، می‌بینیم که تابع super، تابع output مربوط به کلاس Person را هم صدا می‌زند و این‌گونه است که هم پیام مربوط به تابع output کلاس Engineer و هم پیام مربوط به تابع output کلاس Person با توجه به ترتیبی که آمده‌اند، صدا زده می‌شوند.
</div>

##### 2.10.3.2. Multi-Inheritance

In [ ]:
class Rooster:
    pass

class Hen:
    pass

class Chick(Rooster, Hen):
    pass

<div style = "direction:rtl">
در مثال بالا، کلاس Chick هم‌زمان از کلاس‌های Rooster و Hen ارث‌ برده‌ است و می‌تواند از ویژگی‌های هر دوی این کلاس‌ها استفاده کند.
</div>

<div style = "direction:rtl">
حال فرض کنید که کلاس‌هایی که از آن‌ها ارث‌بری کرده‌ایم؛ دارای ویژگی‌ مشترکی باشند. در این صورت، با صدا زدن آن ویژگی در کلاس فرزند، آن ویژگی از بین کدام یک از کلاس‌های پدر انتخاب می‌شود؟
پاسخ این است که در صورتی که کلاس‌هایی که از آن ارث برده شده ویژگی‌های یکسانی داشته باشند، آن ویژگی از اولین کلاسی که نوشته شده ارث برده می‌شود.
</div>

In [14]:
class Rooster:
    def name(self):
        print('In Rooster class.')

class Hen:
    def name(self):
        print('In Hen class.')
    def hello(self):
        print('Hello my baby!')

class Chick(Rooster, Hen):
    pass

x = Chick()
x.name()
x.hello()

In Rooster class.
Hello my baby!


###### 2.10.3.2.1. using "super"

In [12]:
class Shape:
    def __init__(self):
        print('Initialize from class Shape')

class Rectangle(Shape):
    def __init__(self):
        print('Initialize from class Rectangle')
        Shape.__init__(self)

class Rhombus(Shape):
    def __init__(self):
        print('Initialize from class Rhombus')
        Shape.__init__(self)

class Square(Rectangle, Rhombus):
    def __init__(self):
        Rectangle.__init__(self)
        Rhombus.__init__(self)

squ = Square()

Initialize from class Rectangle
Initialize from class Shape
Initialize from class Rhombus
Initialize from class Shape


<div style = "direction:rtl">
اگر دقت کرده باشید می‌بینید که تابع ‍‍__init__ کلاس Shape در اینجا ۲ بار تکرار شده است و این مسئله اشتباه است. چون درست است که هر دو کلاس Rectangle و Rhombus از کلاس Shape ارث‌بری کرده‌اند ولی برای کلاس Square نباید تابع مربوط به کلاس Shape ۲ بار تکرار می‌شد. حالا اگر از شیٔ super استفاده کنیم این مشکل رفع می‌شود. به کد زیر دقت کنید:
</div>

In [13]:
class Shape:
    def __init__(self):
        print('Initialize from class Shape')

class Rectangle(Shape):
    def __init__(self):
        print('Initialize from class Rectangle')
        super().__init__()

class Rhombus(Shape):
    def __init__(self):
        print('Initialize from class Rhombus')
        super().__init__()

class Square(Rectangle, Rhombus):
    def __init__(self):
        super().__init__()

squ = Square()

Initialize from class Rectangle
Initialize from class Rhombus
Initialize from class Shape


<div style = "direction:rtl">
در نتیجه بهتر است در ارث بری از شیٔ super استفاده کنید که کدتان دچار این چنین مشکلات احتمالی نشود.
</div>

#### 2.10.4. getter and setter

<div style = "direction:rtl">
getter و setter در بسیاری از زبان‌های شئ‌گرا استفاده می‌شوند. اگر تجربه کار با دیگر زبان‌های برنامه‌نویسی شئ‌گرا مانند java را داشته باشید شاید تصور کنید روش مناسب پیاده سازی کلاس، استفاده از متغیرهای خصوصی است؛ اما در پایتون ترجیح بر این است که بیشتر از متغیرهای عمومی استفاده شود.
</div>

In [27]:
class First:

    def __init__(self, x):
        self.__x = x

    def get_x(self):
        return self.__x

    def set_x(self, x):
        self.__x = x
        pass
    pass
obj1 = First(42)
obj2 = First(4711)
print(obj1.get_x())
obj1.set_x(50)
print(obj1.get_x())

42
50


In [28]:
obj1.set_x(obj1.get_x()+obj2.get_x())
print(obj1.get_x())

4761


<div style = "direction:rtl">
به قطعه کد بالا دقت کنید. مسلما عبارت obj1.set_x(obj1.get_x() + obj2.get_x()) نسبت به obj1.x = obj1.x + obj2.x عبارت ناخواناتری است.
    <br>
    پس اجازه دهید کلاسی مانند کلاس بالا را به روشی پایتونی‌تر بازنویسی کنیم:
</div>

In [29]:
class Second:

    def __init__(self, x):
        self.x = x
        pass
    pass
obj1 = Second(42)
obj2 = Second(4711)
print(obj1.x)
obj1.x = 43
obj1.x = obj1.x + obj2.x
print(obj1.x)

42
4754


<div style = "direction:rtl">
مسلما این کد از حالت قبل خواناتر است؛ اما ممکن است بگویید: "خب، پس Data Encapsulation وجود نداره؟ ..." در جواب باید گفت بله، در این مورد data Encapsulation وجود ندارد؛ در واقع به آن نیازی نیست. تنها کاری که ‍get_x و set_x در مثال اولیه انجام می‌داد، دادن و گرفتن متغیر بدون هیج کار اضافه‌ای بود.
<br>
ولی اگر در آینده بخواهیم پیاده سازی را تغییر دهیم چه؟ این مسئله‌ی جدی‌ای است. فرض کنید بخواهیم پیاده‌سازی را به این صورت تغییر دهیم که:
<br>
متغیر x مقادیری بین ۰ و ۱۰۰۰ می‌تواند داشته باشد، اگر مقداری بزرگتری از ۱۰۰۰ به آن assign شد باید برابر ۱۰۰۰ قرار گیرد و اگر برابر مقداری کمتر از ۰ قرار گرفت باید برابر ۰ شود.
برای حالت اول (کلاس First) کار راحت‌تر است و می‌توان کد را مطابق مورد پایین تغییر داد:
</div>

In [ ]:
class First:

    def __init__(self, x):
        self.set_x(x)

    def get_x(self):
        return self.__x

    def set_x(self, x):
        if x < 0:
            self.__x = 0
        elif x > 1000:
            self.__x = 1000
        else:
            self.__x = x

In [30]:

obj1 = First(1001)
print(obj1.get_x())

obj2 = First(15)
print(obj2.get_x())

obj3 = First(-1)
print(obj3.get_x())

1001
15
-1


<div style = "direction:rtl">
اما اگر کلاس را مانند حالت دوم (کلاس Second) طراحی می‌کردیم و قصد داشتیم تغییرات گفته شده را برروی آن اعمال کنیم، چه؟ اگر سعی کنیم این کلاس را با روش قبلی جایگزین کنیم، کلاس جدید باعث ایجاد خطا در سایر قسمت‌های کد می‌شود (متغیر x در آن قسمت‌ها در دسترس نمی‌باشد). به همین علت است که در بعضی از زبان های شئ‌گرا توصیه می‌شود از متغیرهای خصوصی استفاده شود. ولی در پایتون نیاز به رعایت چنین اصلی ندارید.
<br>
پایتون برای حل این مشکل راه‌حلی ارائه می‌کند که متفاوت با این زبان‌ها است. راه حل پایتونی، استفاده از ‍properties است.
</div>

In [33]:
class Second:

    def __init__(self, x):
        self.x = x

    @property
    def x(self):
        print("---> getter <---")
        return self.__x

    @x.setter
    def x(self, x):
        print("---> setter <---")
        if x < 0:
            self.__x = 0
        elif x > 1000:
            self.__x = 1000
        else:
            self.__x = x


<div style = "direction:rtl">
setter:این متد به عنوان تنظیم‌کننده (setter) برای یک متغیر عمل می‌کند. قبل از آن باید از @varible_name.setter استفاده شود و زمانی که مقدار به متغیر ‍assign شود صدا زده می‌شود.
<br>
‏property:این متد کاملا مشابه getter برای یک متغیر عمل می‌کند. فقط باید قبل از آن از @property استفاده شود.
</div>

In [35]:

obj1 = Second(1001)
print(obj1.x)



obj2 = Second(-73)
print(obj2.x)



obj3 = Second(17)
print(obj3.x)


obj3.x = 25
print(obj3.x)

---> setter <---
---> getter <---
1000
---> setter <---
---> getter <---
0
---> setter <---
---> getter <---
17
---> setter <---
---> getter <---
25


<div style = "direction:rtl">
شاید به اشتباه فکر کنید که هر attribute‍ ، چه public و چه private نیاز به property‍ (یا getter و setter ) نظیر دارد.
<br>
اما حتی در زبان های شئ‌گرای دیگر نیز این ایده‌ی درستی نیست. دلیل اصلی، این است که بسیاری از attribute ها صرفا کاربرد داخلی دارند و یا نیازی به بررسی شرایطی مانند چیزی که در بالا گفته شده ندارند. استفاده از این متدها در این موارد تنها خوانایی کد را کاهش می‌دهد.
<br>
برای مثال در کد زیر دو متغیر __potential_physical و ‍‍‍‍__potential_psychic فقط استفاده‌ی داخلی دارند. هم‌چنین نشان داده شده که یک مقدار یک property می‌تواند از سایر ویژگی‌ها استنباط شود.
</div>

In [36]:
class Robot:

    def __init__(self, name, build_year, lk = 0.5, lp = 0.5 ):
        self.name = name
        self.build_year = build_year
        self.__potential_physical = lk  # private attribute
        self.__potential_psychic = lp # private attribute

    @property
    def condition(self):
        s = self.__potential_physical + self.__potential_psychic
        if s <= -1:
            return "I feel miserable!"
        elif s <= 0:
            return "I feel bad!"
        elif s <= 0.5:
            return "Could be worse!"
        elif s <= 1:
            return "Seems to be okay!"
        else:
            return "Great!" 

Wall_E= Robot("Wall-E", 1979, 0.2, 0.4 )
Hal = Robot("Hal", 1993, -0.4, 0.3)
print(Wall_E.condition)
print(Hal.condition)

# output
# Seems to be okay!
# I feel bad!

Seems to be okay!
I feel bad!


<div style = "direction:rtl">
در انتها برای اینکه ابهامات در مورد public/private attributeها و سایر موارد تا حد امکان برطرف شود، مراحل زیر را طی کنید:
<br>
اول به این سوال پاسخ بدهید که آیا استفاده‌کنندگان کلاس نیاز به دسترسی به مقدار متغیر دارند؟
    <br>
اگر خیر، بهتر است که متغیرها به صورت private تعریف شوند.
    <br>
اگر بله، باید متغیرها به صورت public تعریف شوند.
    <br>
اگر و فقط اگر مجبور به انجام برخی بررسی‌ها یا تغییر شکل داده‌ها باشیم از @property استفاده می‌کنیم (البته هم‌چنان می‌توان از آن برای ایجاد متغیرهای استنباط‌شده استفاده کرد.).
</div>

#### 2.10.5. Instrospection

##### 2.10.5.1. "dir" function

<div style = "direction:rtl">
این تابع مهم‌ترین و ابتدایی‌ترین تابع برای introspection است که به عنوان ورودی یک شی می‌گیرد و لیست خصوصیات (attributes) شی داده شده را برمی‌گرداند (توجه کنید که در پایتون همه چیز حتی تابع‌ها شی هستند و از کلاسobject ارث برده‌اند).
</div>

In [40]:
class Person():
    def get_age(self):
            pass
    name = 'Saeid'
    pass
person = Person()
print(dir(person))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'get_age', 'name']


<div style = "direction:rtl">
دقت کنید که در خروجی تابع dir تعداد زیادی خصوصیت‌ وجود دارد که به صورت پیش‌فرض در کلاس object وجود دارد و همه اشیا با ارث‌بری از کلاس object این خصوصیات را دارا هستند (مانند خروجی‌های چاپ شده در بالا).
</div>

<div style = "direction:rtl">
اگر تابع dir را بدون ورودی صدا کنید، لیست متغیر‌های محلی محدود‌ه‌ای که در آن فراخوانده می‌شود را خروجی می‌دهد.
</div>

In [1]:
number = 100
def func():
    number_2 = 200
    print(dir())
    pass
func()

['number_2']


##### 2.10.5.2. "type()" function

<div style = "direction:rtl">
این تابع به دو شکل قابل استفاده است.
<br>
در شکل اول، به آن یک شی ورودی داده شده و تابع جنس (type) آن را در همان لحظه از اجرای برنامه بر‌می‌گرداند.
</div>

In [2]:
a = 100
print(type(a))

a = [1, 2, 3]
print(type(a))

def func():
    pass

print(type(func))

print(type(type))

<class 'int'>
<class 'list'>
<class 'function'>
<class 'type'>


<div style = "direction:rtl">
دقت کنید که جنس a در هنگام اجرای برنامه عوض شده و تابع type جنس آن را دو مقدار متفاوت برمی‌گرداند.
<br>
تابع type در اصل یک کلاس است که توانایی صداشدن (calling) دارد
</div>

<div style = "direction:rtl">
شکل دوم این تابع برای ساخت یک جنس (type) جدید به کار می‌رود.
<br>
برای این کار به ترتیب سه آرگومان زیر را ورودی می‌گیرد:
<br>
نام: یک رشته که نام جنس جدیدی را که می‌خواهیم بسازیم مشخص می‌کند.
    <br>
پایه‌ها‌ (bases): یک چندتایی که شامل کلاس‌هایی است که از آن‌ها ارث می‌برد.
    <br>
ویژگی‌ها: یک لغت‌نامه که خصوصیات آن جنس را مشخص می‌کند. هر کلید آن، یک ویژگی و هر مقدار، مقدار پیش‌فرض آن ویژگی را مشخص می‌کند.
    <br>
در نهایت هم type جدید با خصوصیات داده شده را خروجی می‌دهد.
</div>

In [47]:
def set_name(self, name):
    self.name = name

Kid = type('MyNewType', (object,), {'age': 4, 'height': 130, 'name': 'default', 'set_name': set_name})
kid = Kid()
print(kid.age)

print(kid.height)

print(kid.name)

kid.set_name('amir')
print(kid.name)
print(type(Kid))
print(type(kid))

4
130
default
amir
<class 'type'>
<class '__main__.MyNewType'>


<div style = "direction:rtl">
جنس Kid دارای سازنده پیش‌فرض است زیرا از object ارث برده است.
<br>
دقت کنید که با کمک لغت‌نامه‌ی ویژگی‌ها می‌توان حتی یک تابع را به عنوان خصوصیات جنس ساخته شده قرار داد.
</div>

<div style = "direction:rtl">
هم‌چنین جنس جدید، همه ویژگی‌هایی که پدرهاش دارند را حفظ می‌کند:
</div>

In [42]:
class Person():
    name = ''
    age = 8
    pass

Kid = type('Kid', (Person,), {'height': 130})
kid = Kid()

print(kid.name)
print(kid.age)
print(dir(kid))


8
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'age', 'height', 'name']


<div style = "direction:rtl">
در این‌جا می‌بینید که ‍‍Kid دو ویژگی ‍‍name و age را هم دارد.
</div>

##### 2.10.5.3. Inheritance-Introseption function

###### 2.10.5.3.1. "isinstance()"

<div style = "direction:rtl">
تابع isinstance() یک شی و یک کلاس (یا چندین کلاس) یا یک تایپ (type) (یا چندین تایپ) ورودی می‌گیرد و در جواب متغیری منطقی بر می‌گرداند که نشان می‌دهد این شئ، یک عضو از آن کلاس هست یا نه.
</div>

In [3]:
class Animal():
    def __init__(self, name, type):
        self.name = name
        self.type = type
        pass
    pass
class Fox(Animal):
    def __init__(self, name):
        self.name = name
        self.type = 'Fox'

class Person():
    def __init__(self, name, age):
        self.name = name
        self.age = age

fox = Fox('Alex')
print(isinstance(fox, Fox))

print(isinstance(fox, Animal))

print(isinstance(fox, Person))

print(isinstance(fox, (Animal, Person)))

print(isinstance(fox, (list, Person)))

True
True
False
True
False


In [4]:
print(isinstance(2, int))

print(isinstance(2, str))

print(isinstance(2, (str, list, int, float)))

print(isinstance('Hello', int))

print(isinstance("Hello", (float, str, int, list, dict, tuple)))

True
False
True
False
True


###### 2.10.5.3.2. "issubclass()"

<div style = "direction:rtl">
همین‌طور تابع issubclass() دو کلاس ورودی می‌گیرد و در جواب متغیر منطقی بر می گرداند که نشان می‌دهد کلاس اول از فرزندان کلاس دوم هست یا نه.
</div>

In [5]:
class Animal():
    def __init__(self, name, type):
        self.name = name
        self.type = type

class Bird(Animal):
    def __init__(self, name):
        self.name = name
        self.type = 'Bird'

class Owl(Bird):
    def __init__(self, name):
        self.name = name
        self.type = 'Bird'
        self.bird_type = 'Owl'

class Person():
    def __init__(self, name, age):
        self.name = name
        self.age = age

print(issubclass(Bird, Animal))

print(issubclass(Owl, Animal))

print(issubclass(Animal, Owl))

print(issubclass(Person, Animal))

print(issubclass(Animal, object))

print(issubclass(Owl, (Animal, Person)))

print(issubclass(Bird, (Person, list, Owl)))

True
True
False
False
True
True
False


#### 2.10.6. Reflection

methods also in this topic are included in attributes.

##### 2.10.6.1. "getattr()" function

<div style = "direction:rtl">
این تابع دو آرگومان object و name را ورودی می‌گیرد و object.name را خروجی می‌دهد. برای مثال:
</div>

In [6]:
class A():
    def __init__(self, age, name):
        self.age = age
        self.name = name
        pass
    pass

a = A(12, 'amir')
print(getattr(a, 'age'))

s = input()
print(getattr(a, s))

12


 name


amir


<div style = "direction:rtl">
در اصل تابع getattr، تابع‌ object.__getattr__() را صدا می‌کند که در کلاس object به صورت پیش‌فرض تعریف شده است.
</div>

<div style = "direction:rtl">
این تابع دارای یک آرگومان غیرضروری (optional) به نام پیش‌فرض یا default است که اگر شی داده شده خصوصیت مورد نظر را نداشت این مقدار برگردانده می‌شود (در صورتی که این ورودی داده نشود و خصوصیت وجود نداشته باشد، برنامه یک استثنا پرتاب می‌کند).
</div>

In [45]:
a = 0
print(getattr(a, 'age', 12))

12


##### 2.10.6.2. "setattr()" function

<div style = "direction:rtl">
این تابع سه آرگومان دارد که اولی یک شی، دومی نام خصوصیت و سومی مقدار آن را ورودی می‌گیرد و در شی داده شده مقدار خصوصیت داده شده را برابر با مقدار مورد نظر قرار می‌دهد.
</div>

In [17]:
class A():
    def __init__ (self, age):
        self.age = age
        pass
    def set_age(self, age):
        self.age = age
        pass
    pass
a = A(10)
setattr(a, 'age', 12) # changing attribute
setattr(a, 'name', 'amir') # making attribute

print(a.name + " , " + str(a.age))
setattr(a, "set_age", 15)
print(a.set_age)

amir , 12
15


In [12]:
b = A(14)
print(b.name)

AttributeError: 'A' object has no attribute 'name'

----------------------------------
- __تعریف توابع به صورت پویا__

In [13]:
class A():
    def __init__(self):
        self.attrs = {'name': 'amir', 'age': 12, 'grade': 'A'}

    def __getattr__(self, attr):

        if attr in self.attrs:
            return self.attrs[attr]

        def f():
            return getattr(self, attr[4:])

        return f
    pass


a = A()

print(a.get_name())
print(a.get_age())
print(a.get_grade())

amir
12
A


<div style = "direction:rtl">
دقت کنید که . و ‍getattr() تابع __getattr__() را صدا می‌کنند. با over ride کردن این تابع توانستیم توابع گیرنده (getter) کلاس را بسازیم.
    <br>
    در واقع در کد بالا،‌ اگر ویژگی attr در میان ویژگی‌ها وجود داشت مقدار آن برگردانده می‌شود و در غیر این صورت ۴ حرف اول آن که برابر با get_ است حذف می‌شود و تابعی که آن مقدار را برمی‌گرداند، برگردانده می‌شود.
</div>

------------------------------

#### 2.10.7. Dunder Methods (Magic Methods)

<div>
Dunder Methods are methods with the name format: __methodname__
</div>

<div style = "direction:rtl">
کلاس زیر را در نظر بگیرید:
</div>

In [2]:
class Movie:
    def __init__(self, name, release_year):
        self.name = name
        self.release_year = release_year

In [3]:
favorite_movie = Movie('Fight Club', 1999)
print(dir(favorite_movie))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'name', 'release_year']


<div style = "direction:rtl">
همانطور که مشاهده می‌کنید، به غیر از دو ویژگی آخر لیست که ما به این شیء اختصاص دادیم بقیه عناصر همگی اسامی داندر متدهایی هستند که به واسطه ارث‌بری از کلاس object وجود دارند؛
</div>

<h5> 2.10.7.1. __str__ </h5>

<div style = "direction:rtl">
اگر شیء favorite_movie را چاپ کنیم خروجی چه خواهد بود؟
</div>

In [4]:
print(favorite_movie)

<div style = "direction:rtl">
شاید برای بسیاری از افراد این خروجی که به صورت پیش‌فرض برای همه اشیاء اعمال شده است، خوشایند نباشد. به عنوان مثال برای اشیاء کلاس Movie می‌خواهیم که با چاپ کردن آن‌ها اسم فیلم را در خروجی ببینیم. خوشبختانه با استفاده از جادوی داندر متدها می‌توانیم این مشکل را حل کنیم:
</div>

In [6]:
class Movie:
    def __init__(self, name, release_year):
        self.name = name
        self.release_year = release_year

    def __str__(self):
        return self.name

<div style = "direction:rtl">
همانطور که مشاهده می‌کنید متد __str__ را به شکلی بازنویسی کردیم که اگر روی هر شیء از کلاس Movie فراخوانی شود نام آن شیء را خروجی دهد.
</div>

In [7]:
favorite_movie = Movie('Fight Club', 1999)
favorite_movie.__str__()

print(str(favorite_movie))

print(favorite_movie)

Fight Club
Fight Club


<div style = "direction:rtl">
در واقع تابع print هر شیئی که به آن ورودی داده شود، خروجی تابع str آن را چاپ می‌کند و تابع str هم کاملا طبق پیاده‌سازی داندر متد __str__ عمل می‌کند. یعنی وقتی str(favorite_movie) را اجرا کنیم، خروجی favorite_movie.__str__() خروج داده می‌شود.
</div>

##### 2.10.7.2. Overloading of operators

<h6> 2.10.7.2.1. __lt__ </h6>

In [5]:
class Movie:
    def __init__(self, name, release_year):
        self.name = name
        self.release_year = release_year

    def __str__(self):
        return self.name

    def __lt__(self, other_object):
        return self.release_year < other_object.release_year 

<div style = "direction:rtl">
همانطور که مشاهده می‌کنید متد __lt__ را به شکلی بازنویسی کردیم که عملگر <، برای مقایسه سال انتشار فیلم‌ها به کار گرفته شود.
</div>

<div style = "direction:rtl">
وقتی se7en < hangover را اجرا کنیم، خروجی se7en.__lt__(hangover) خروج داده می‌شود.
<br>
به همین شکل می‌توانیم عملگرهای مقایسه‌ای دیگر را هم با استفاده از داندر مخصوص آن‌ها برای کلاس خود تعریف کنیم:
    <br>
    <table dir="auto" class="ui unstackable table">
<thead>
<tr>
<th align="center">نام عملگر</th>
<th align="center">عبارت</th>
<th align="center">داندر متد</th>
</tr>
</thead>
<tbody><tr>
<td align="center">کوچک‌تر</td>
<td align="center"><code dir="ltr">a &lt; b</code></td>
<td align="center"><code dir="ltr">__lt__</code></td>
</tr>
<tr>
<td align="center">بزرگ‌تر</td>
<td align="center"><code dir="ltr">a &gt; b</code></td>
<td align="center"><code dir="ltr">__gt__</code></td>
</tr>
<tr>
<td align="center">کوچک‌تر یا مساوی</td>
<td align="center"><code dir="ltr">a &lt;= b</code></td>
<td align="center"><code dir="ltr">__le__</code></td>
</tr>
<tr>
<td align="center">بزرگ‌تر یا مساوی</td>
<td align="center"><code dir="ltr">a &gt;= b</code></td>
<td align="center"><code dir="ltr">__ge__</code></td>
</tr>
<tr>
<td align="center">مساوی</td>
<td align="center"><code dir="ltr">a == b</code></td>
<td align="center"><code dir="ltr">__eq__</code></td>
</tr>
<tr>
<td align="center">نامساوی</td>
<td align="center"><code dir="ltr">a != b</code></td>
<td align="center"><code dir="ltr">__ne__</code></td>
</tr>
</tbody></table>
</div>

<div style = "direction:rtl">
می‌دانیم که اگر بعد از اسم تابع یا متد () بگذاریم، فراخوانی انجام می‌شود. طبق روال قبلی، این سناریو را برای شیئی از کلاس Movie تصور کنید و نتیجه را پیش‌بینی کنید.
</div>

<div style = "direction:rtl">
همانطور که می‌بینید برنامه متوقف می‌شود.
</div>

<h6> 2.10.7.2.2. __add__ </h6>

<div style = "direction:rtl">
    همانطور که می‌دانید در پایتون اگر عملگر + را:
<ul dir="auto">
<li>بین دو <strong>عدد</strong> به کار ببریم، در خروجی جمع ریاضی دو عدد را نشان می‌دهد.</li>
<li>بین دو <strong>رشته</strong> به کار ببریم، در خروجی رشته اول را به رشته دوم می‌چسباند.</li>
<li>بین دو <strong>لیست</strong> به کار ببریم، در خروجی عناصر لیست دوم را در ادامه عناصر لیست اول قرار می‌دهد.</li>
</ul>
</div>

<div style = "direction:rtl">
این تفاوت عملکرد برای اشیاء مختلف، به دلیل پیاده‌سازی‌های متفاوت داندر متد __add__ می‌باشد. برای مثال کلاس زیر را در نظر بگیرید:
</div>

In [7]:
class FootballTeam:
    def __init__(self, name, cups_number):
        self.name = name
        self.cups_number = cups_number

    def __add__(self, other_object):
        return self.cups_number + other_object.cups_number

<div style = "direction:rtl">
در حالت عادی وقتی عملگر + بین دو شیء از کلاس FootballTeam قرار می‌گیرد، برنامه متوقف می‌شود به دلیل اینکه نمی‌داند دقیقا چه چیزی را باید جمع بزند! ما با تعریف داندر متد __add__ وظیفه عملگر + را مشخص کرده‌ایم. پس انتظار داریم بعد از تعریف این متد، عملگر + تعداد جام‌های قهرمانی تیم‌ها را با یکدیگر جمع بزند:
</div>

<div style = "direction:rtl">
به همین شکل می‌توانیم عملگرهای ریاضی و منطقی دیگر را هم با استفاده از داندر مخصوص آن‌ها، برای کلاس خود تعریف کنیم:
    <br>
    <table dir="auto" class="ui unstackable table">
<thead>
<tr>
<th align="center">نام عملگر</th>
<th align="center">عبارت</th>
<th align="center">داندر متد</th>
</tr>
</thead>
<tbody><tr>
<td align="center">جمع</td>
<td align="center"><code dir="ltr">a + b</code></td>
<td align="center"><code dir="ltr">__add__</code></td>
</tr>
<tr>
<td align="center">تفریق</td>
<td align="center"><code dir="ltr">a - b</code></td>
<td align="center"><code dir="ltr">__sub__</code></td>
</tr>
<tr>
<td align="center">ضرب</td>
<td align="center"><code dir="ltr">a * b</code></td>
<td align="center"><code dir="ltr">__mul__</code></td>
</tr>
<tr>
<td align="center">تقسیم اعشاری</td>
<td align="center"><code dir="ltr">a / b</code></td>
<td align="center"><code dir="ltr">__truediv__</code></td>
</tr>
<tr>
<td align="center">تقسیم صحیح</td>
<td align="center"><code dir="ltr">a // b</code></td>
<td align="center"><code dir="ltr">__floordiv__</code></td>
</tr>
<tr>
<td align="center">باقی‌مانده</td>
<td align="center"><code dir="ltr">a % b</code></td>
<td align="center"><code dir="ltr">__mod__</code></td>
</tr>
<tr>
<td align="center">توان</td>
<td align="center"><code dir="ltr">a ** b</code></td>
<td align="center"><code dir="ltr">__pow__</code></td>
</tr>
<tr>
<td align="center">شیفت چپ</td>
<td align="center"><code dir="ltr">a &lt;&lt; b</code></td>
<td align="center"><code dir="ltr">__lshift__</code></td>
</tr>
<tr>
<td align="center">شیفت راست</td>
<td align="center"><code dir="ltr">a &gt;&gt; b</code></td>
<td align="center"><code dir="ltr">__rshift__</code></td>
</tr>
<tr>
<td align="center">AND</td>
<td align="center"><code dir="ltr">a &amp; b</code></td>
<td align="center"><code dir="ltr">__and__</code></td>
</tr>
<tr>
<td align="center">OR</td>
<td align="center"><code dir="ltr">a ا b</code></td>
<td align="center"><code dir="ltr">__or__</code></td>
</tr>
<tr>
<td align="center">XOR</td>
<td align="center"><code dir="ltr">a ^ b</code></td>
<td align="center"><code dir="ltr">__xor__</code></td>
</tr>
<tr>
<td align="center">NOT</td>
<td align="center"><code dir="ltr">~a</code></td>
<td align="center"><code dir="ltr">__invert__</code></td>
</tr>
</tbody></table>
</div>

<div style = "direction:rtl">

</div>

<h5> 2.10.7.3. __call__ </h5>

<div style = "direction:rtl">
می‌دانیم که اگر بعد از اسم تابع یا متد () بگذاریم، فراخوانی انجام می‌شود. طبق روال قبلی، این سناریو را برای شیئی از کلاس Movie تصور کنید و نتیجه را پیش‌بینی کنید.
</div>

In [8]:
scarface = Movie('Scarface', 1983)
scarface()

TypeError: 'Movie' object is not callable

<div style = "direction:rtl">
همانطور که می‌بینید برنامه متوقف می‌شود.
</div>

<div style = "direction:rtl">
    در پایتون فقط توابع نیستند که می‌توانند صدا شوند. هر شیئی که تابع __call__() در آن تعریف شده باشد، می‌تواند به صورت obj() صدا شود.
    <br>
داندر متد __call__ تعیین می‌کند که با قرار گرفتن () بعد از یک شیء، چه عملی انجام شود. اکنون اگر داندر متد __call__ را بدین صورت بازنویسی کنیم:
</div>

In [30]:
class A:
    def __call__(self, x):
        return x**2
        pass
    pass


a = A()
a(20)

400

In [10]:
class Movie:
    def __init__(self, name, release_year):
        self.name = name
        self.release_year = release_year

    def __str__(self):
        return self.name

    def __lt__(self, other_object):
        return self.release_year < other_object.release_year 

    def __call__(self):
        return 'Say Hello to My Little Friend!😈'

In [12]:
scarface = Movie('Scarface', 1983)

print(scarface.__call__())

print(scarface())


Say Hello to My Little Friend!😈
Say Hello to My Little Friend!😈


<div style = "direction:rtl">
وقتی scarface() را اجرا کنیم، خروجی scarface.__call__() خروج داده می‌شود.
</div>

<h5> 2.10.7.4. __len__ </h5>

<div style = "direction:rtl">
قطعا تا به حال بارها از تابع len() استفاده کرده‌اید. رفتار این تابع به نحوه پیاده‌سازی داندر متد __len__ بستگی دارد. برای مثال اگر بخواهیم هنگام استفاده از این تابع برای لیست‌ها تعداد عناصر یکتا را نشان دهد می‌توانیم بدین شکل عمل کنیم:
</div>

In [13]:
class CustomList(list):
    def __len__(self):
        return len(set(self))

<div style = "direction:rtl">
در نتیجه تابع len در نشان دادن طول لیست (CustomList) فقط عناصر یکتا را به حساب می‌آورد:
</div>

In [16]:
my_list = CustomList([1, 1, 1, 1, 1, 684])

print(my_list.__len__())

print(len(my_list))

2
2


<div style = "direction:rtl">
وقتی len(my_list) را اجرا کنیم، خروجی my_list.__len() خروج داده می‌شود.
</div>

<h5> 2.10.7.5. __iter__ and __next__ </h5>

<div style = "direction:rtl">
اگر دقت کرده باشید اکثر اشیا‌یی که شامل چند شئ دیگر درون خود هستند (container objects) مانند لیست، رشته، لغت‌نامه، چندتایی و ... می‌توانند توسط دستور for پیمایش شوند.
<br>
دستور for برای پیمایش کردن یک شئ، تابع iter() آن را صدا می‌زند. این تابع باید یک پیمایش‌گر (iterator) برگرداند. این پیمایش‌گر باید یک تابع __next__() داشته باشد که با صدا کردن آن، پیمایش‌گر یک واحد حرکت کند. در نهایت اگر به انتها رسید یک خطای StopIteration‍‍ را صدا کند. درضمن می‌توان با تابع next(a) تابع a.__next__() را صدا کرد. برای درک بهتر این موضوع به مثال زیر دقت کنید.
</div>

In [19]:
ls = [1, 2, 4]
it = iter(ls)
print(it)

print(next(it))

print(next(it))

print(next(it))

print(next(it))


1
2
4


StopIteration: 

<div style = "direction:rtl">
    با وقوع خطای StopIteration پیمایش متوقف می شود .
    <br>
حال یک کلاس تعریف می‌کنیم که قابلیت پیمایش شدن دارد و اعضای یک لیست را به صورت تصادفی می‌چیند.
</div>

In [18]:
import random

class RandomShuffle:
    def __init__(self, data):
        self.data = data

    def __iter__(self):
        return self

    def __next__(self):
        if len(self.data) == 0:
            raise StopIteration

        index = random.randint(0, len(self.data)-1)
        index = int(index)
        return self.data.pop(index)

number = [1, 2, 3, 4, 5, 6]
number_random = RandomShuffle(number)

print(*number)
print(*number_random)

1 2 3 4 5 6
2 1 3 5 6 4


<div style = "direction:rtl">
تابع randint(s,e) از کلاس random یک عدد تصادفی درون بازه [s,e] خروجی می‌دهد.
</div>

------------------------
- __Underscore In Python__

In [2]:
# Ignore a value of specific location/index
for _ in range(10):
    print ("Test")
    pass

# Ignore a value when unpacking
a,b,_,_ = (1, 2, 3, 4)
print(a, b)

Test
Test
Test
Test
Test
Test
Test
Test
Test
Test
1 2


- After a name

Python has their by default keywords which we can not use as the variable name. To avoid such conflict between python keyword and variable we use underscore after name

In [3]:
class MyClass():
    def __init__(self):
        print ("OWK")
        pass
    pass

def my_defination(var1 = 1, class_ = MyClass):
    print (var1)
    print (class_)

my_defination()

1
<class '__main__.MyClass'>


- Before a name

Leading Underscore before variable/function/method name indicates to programmer that It is for internal use only.
Here name prefix by underscore is treated as non-public. If specify from Import * all the name starts with _ will not import. Python does not specify truly private so this ones can be call directly from other modules if it is specified in __all__, We also call it weak Private

-----------------------------
### 2.11. Module

#### 2.11.1. Module 

<div style = "direction:rtl">
ماژول‌ها به شما این امکان را می‌دهند که پروژه خود را راحت‌تر مدیریت کنید. به‌طور کلی ماژول‌ یک فایل پایتونی است که شامل مجموعه‌ای از ویژگی‌ها از قبیل کلاس‌ها، توابع، متغیرها و حتی کدهای قابل اجرا (runnable code) می‌باشد. فرض کنید دو فایل پایتونی به‌نام test.py و main.py دارید. حال اگر از ویژگی‌های test.py در main.py استفاده کنید، فایل test.pyبه عنوان یک ماژول در نظر گرفته شده است. اما برای این کار ابتدا باید test.py را به main.pyاضافه کنید.
</div>

- Standard module : means python itself supports it, and the module is with python from begining.

#### 2.11.2. "import"

<div style = "direction:rtl">
این دستور تمام ویژگی‌هایی که در یک فایل پایتون مثل کلاس‌ها، توابع، متغیرها و ... قرار دارند را به برنامه ما اضافه می‌کند. برای استفاده از آنها کافی‌ست اول نام آن فایل یا ماژول و سپس نام ویژگی موردنظر را بنویسید. برای مثال بعد از اضافه‌ کردن کتابخانه ‍‍math به این شکل می‌توانستید به همه توابع و متغیرهای آن دسترسی داشته‌ باشید و یا حتی آن‌ها را تغییر دهید. البته توجه کنید که این تغییر دادن به صورت محلی است یعنی بار بعدی که کتابخانه را اضافه کنیم همان مقدار قبلی را دریافت خواهیم کرد.
<br>
برای فهمیدن بیشتر این موضوع فرض کنید پروژه‌ای داریم که ساختار آن به شکل زیر است :
</div>

<div style = "direction:rtl">
و در فایل test.py کد زیر وجود دارد.
</div>

<div style = "direction:rtl">
حالا فرض کنید می‌خواهیم در فایل main.py به این سه ویژگی که در فایل test.py قرار دارند دسترسی پیدا کنیم. برای این کار می‌توانیم با استفاده از دستور import test ویژگی‌های آن فایل را داشته باشیم. برای فهم بیشتر کد زیر را که در main.py نوشته شده را در نظر بگیرید.
</div>

<div style = "direction:rtl">
که با اجرا کردن آن خروجی زیر تولید می‌شود.
</div>

<div style = "direction:rtl">
همان‌طور که می‌بینید در خط بعد از import تابع test_print فایل test.py را صدا زده‌ایم و عبارت test file چاپ شده‌است. پس از آن یک شی از نوع ‍‍Test ساختیم و تابع print آن را صدا زده‌ایم و بعد از آن هم مقدار متغیر a را چاپ کرده‌ایم و همان خروجی که انتظار داشتیم چاپ شده است.
<br>
هم‌چنین می‌توانیم در خود مفسر هم عملیات import کردن را انجام دهیم، سپس به ویژگی‌ها دسترسی داشته باشیم. برای مثال مفسر زیر در همان‌جایی که فایل main.py قرار دارد اجرا شده‌است.
</div>

<div style = "direction:rtl">
همان‌طور که می‌بینید نوع خود test هم module است و می‌توان به چشم متغیر به آن نگاه کرد و مقدار آن را تغییر داد. برای فهم بیشتر مثال زیر را که ادامه مفسر قبلی است در نظر بگیرید.
</div>

<div style = "direction:rtl">
همان‌طور که می‌بینید می‌توانیم مقدار یک ویژگی را تغییر دهیم و پس از این، این مقدار در فراخوانی‌های بعدی تغییر می‌کند. همچنین اگر مقدار خود test را تغییر دهیم، دیگر همان جنس قبلی را ندارد و مقدار آن به کلی تغییر می‌کند. اگر بخواهیم دوباره به مقدار قبلی دسترسی داشته‌باشیم، می‌توانیم دوباره آن را import کنیم. همان‌طور که می‌بینید متغیر a مقدار ۲۰ را دارد و یعنی تغییر قبلی روی آن اعمال شده است. اما اگر این مفسر را ببندید و مفسر دیگری را اجرا کنید با گرفتن مقدار a همان مقدار قبلی، یعنی ۱۰ چاپ می‌شود. یعنی تغییراتی که روی یک module اعمال می‌کنیم به صورت محلی (Local) در آن اعمال می‌شود و بار بعدی که به آن دسترسی پیدا می‌کنیم تغییرات تاثیری نخواهند داشت.
<br>
فرض کنید که فایل پایتونی که می‌خواهید از آن import کنید مستقیما در کنار جایی که از آن import می‌کنید وجود نداشته‌ باشد، در آن صورت می‌توانید آدرس نسبی فایلی که می‌خواهید از آن import شود را بنویسید و آن را به‌جای / با ‍‍. جدا کنید. برای مثال فرض‌ کنید که مفسر را در پوشه‌ای که controller.py در آن قرار دارد اجرا می‌کنیم. در آن صورت می‌توانیم برای دسترسی به test.py از ‍‍main.test استفاده کنید که همان آدرس نسبی test.py است و می‌توانید مثال آن را در زیر ببینید.
</div>

<div style = "direction:rtl">
حال فرض کنید همان محتویات فایل test.py در controller.py هم وجود دارد و می‌خواهیم آن‌ها را از مفسری که در پوشه main قرار دارد، import کنیم. (یعنی در آدرس‌دهی به این نیاز داشته باشیم که به پوشه پدر اشاره کنیم.) در آن صورت می‌توانیم از .. استفاده‌کنیم.
</div>

#### 2.11.3. "from" keyword

<div style = "direction:rtl">
با استفاده از from‍می‌توان یک ویژگی را بدون این که کل module یا همان فایل را اضافه کنیم، import کنیم. در آن صورت برای دسترسی به آن ویژگی کافیست تا آن را به صورت مستقیم صدا کنیم و دیگر نیازی به نوشتن نام module نیست. نحوه استفاده از این دستور به این صورت است که بعد از from نام moduleای که می‌خواهیم از آن import شود را می‌نویسیم(همان آدرس فایل) و بعد از آن کلید واژه import و نام ویژگی‌هایی که می‌خواهیم اضافه شوند را می‌نویسیم. (در صورتی که بخواهیم چند ویژگی اضافه کنیم آن‌ها را با , از هم جدا می‌کنیم.)
<br>
برای مثال به مفسری که در پوشه main اجرا شده‌است توجه‌کنید.
</div>

<div style = "direction:rtl">
همان طور که می‌بینید با استفاده از from توانسته‌ایم ویژگی ‌های test را به طور مستقیم اضافه کنیم. همچنین در صورتی که بخواهیم تمام ویژگی‌های یک module را به طور مستقیم اضافه کنیم می‌توانیم بعد از import کاراکتر * را بنویسیم که نشان می‌دهد می‌خواهیم تمام ویژگی‌ها را اضافه کنیم. برای مثال فرض کنید می‌خواهیم تمام ویژگی‌های کتابخانه math را به طور مستقیم اضافه کنیم، برای این کار می‌توانیم از کاری که در زیر انجام شده استفاده کنیم.
</div>

<div style = "direction:rtl">
همان طور که می‌بینید می‌توانیم به همه ویژگی‌ها به صورت مستقیم دسترسی داشته باشیم و دیگر لازم نیست قبل از اسم هر تابع عبارت ‍‍math. را بنویسیم.
</div>

#### 2.11.3. "as" keyword

<div style = "direction:rtl">
با استفاده از کلیدواژه ‍‍as می‌توان یک ویژگی را به صورت مستقیم اما با یک نام دیگر به برنامه اضافه کرد. شیوه استفاده از این کلیدواژه به این صورت است که بعد از این که به وسیله from آن ویژگی را مشخص کردیم، می‌توانیم از کلیدواژه as استفاده کنیم و بعد از آن نامی را که می‌خواهیم ویژگی داشته باشد می‌نویسیم.
<br>
برای درک بیشتر به مثال زیر توجه کنید.
</div>

<div style = "direction:rtl">
همان‌طور که می‌بینید تابع‌های sin و cos را به شکل برعکس به برنامه اضافه کردیم و بعد از آن هم \piπ را با نام p اضافه کردیم. می‌بینید که دو تابع sin و cos به جای یک‌دیگر کار می‌کنند.
</div>

---------------------------
### 2.12. Debug 

#### 2.12.1. Using "print()"

<div style = "direction:rtl">
در خیلی از موارد امکان استفاده از assert به جای ‍print هم هست.
</div>

In [3]:
def divide(num):
    assert type(num) == int, 'num must be a number'
    n = int(num)
    return 100 / n

print(divide('Yang'))

AssertionError: num must be a number

In [4]:
print(divide(100))


1.0


<div style = "direction:rtl">
در خط اول از تابع divide بررسی می‌شود که آیا جنس آرگومان ورودی (num) برابر int است یا خیر. اگر از این جنس بود به ادامه‌ی برنامه پرداخته می‌شود ولی اگر از جنس دیگری (مانند str یا float یا ...) بود؛ استثنای AssertionError به همراه عبارتی که بعد از , نوشته شده است، پرتاب می‌شود.
</div>

<div style = "direction:rtl">
همانطور که در مثال نشان داده‌شده، متد ‍‍assert که از متدهای پیش‌فرض (built-in) پایتون است، درصورتی که نتیجه عبارت False باشد استثنای ‍AssertionError را پرتاب می‌کند.
<br>
همچنین پایتون به ما این امکان را می‌دهد زمانی که از assert استفاده می‌کنیم با استفاده از پارامتر ‍ -O هیچ‌کدام از assertها را در نظر نگیریم.
</div>

#### pdb

<div style = "direction:rtl">
روش دیگر استفاده از python debugger، pdb است. pdb ابراز دیباگ built-in پایتون است. برای قابلیت های بیشتر بهتر است به سراغ IDE ها بروید، اما گاهی ممکن است ترجیح دهید از pdb یا موارد مشابه مانند: web-pdb ,‌ pudb و ... استفاده کنید
</div>

<div style = "direction:rtl">
<h5> یک مثال ساده </h5>
</div>

<div style = "direction:rtl">
در مثال زیر از pdb برای اجرای گام به گام کد استفاده می‌کنیم.
</div>

<div style = "direction:rtl">
در ابتدا به روش زیر برنامه اجرا می‌کنیم.
</div>

<div style = "direction:rtl">
حالا برنامه از خط اول، خط به خط اجرا می‌کند.
</div>

<div style = "direction:rtl">
با دستور l می‌توان تمام کد را مشاهده کرد.
</div>

<div style = "direction:rtl">
با دستور ‍n می‌توانید خط بعد را اجرا کنید.
</div>

<div style = "direction:rtl">
در هر زمانی با دستور ‍p و نام متغیر می‌توان مقدار متغیر را بررسی کرد.
</div>

<div style = "direction:rtl">
اگر تعداد خطوط برنامه زیاد باشد ممکن است شروع از خط اول زمان‌گیر باشد. در چنین حالتی می‌توان از تابع ()pdb.set_trace برای قرار دادن breakpoint در کد استفاده کرد.
</div>

<div style = "direction:rtl">
اگر برنامه بالا را اجرا کنیم نتیجه‌ای مانند زیر دریافت می‌کنیم:
</div>

<div style = "direction:rtl">
و می‌توانیم از خط print(1000/n) اجرا را ادامه دهیم.
</div>

<div style = "direction:rtl">
    <li>برای موارد بیشتر از این <a href="https://jonskeet.uk/csharp/debugging.html" target="_blank">لینک</a> استفاده کنید.</li>.
    <li>برای آشنایی کامل‌تر با <em>pdb</em> این <a href="https://realpython.com/python-debugging-pdb/" target="_blank">مقاله</a> را مطالعه بفرمایید.</li>
</div>

-------------------------------
## 3. Pakage Managment


- __Python: Module vs Package vs Library vs Framework__

<div>
Module is a file which contains various Python functions and global variables. It is simply just .py extension file which has python executable code.
<br>
Package is a collection of modules. It must contains an __init__.py file as a flag so that the python interpreter processes it as such. The __init__.py could be an empty file without causing issues.
<br>
    It’s important to keep in mind that all packages are modules, but not all modules are packages. Or put another way, packages are just a special kind of module. Specifically, any module that contains a __path__ attribute is considered a package.
    <br>
Library is a collection of packages.
<br>
Framework is a collection of libraries. This is the architecture of the program.
</div>

<div>
Package is a collection of modules. It must contains an __init__.py file as a flag so that the python interpreter processes it as such. The __init__.py could be an empty file without causing issues.
</div>

<div style = "direction:rtl">
در بخش‌های قبل با کتابخانه‌های استاندارد پایتون مانند math آشنا شدید. این کتابخانه‌ها به صورت پیشفرض در کنار پایتون قرار دارند. برخی از کتابخانه‌های مفید (که به طور پیشفرض همراه پایتون نیستند) را باید به سیستم اضافه‌کنیم. مدیریت‌کردن این کتابخانه‌های افزوده معمولا دشوار است.
<br>
می‌توانیم از pip جهت مدیریت این بسته‌‌‌ها استفاده‌کنیم. برای اطلاع از نحوه نصب pip به این‌جا مراجعه‌کنید.
<br>
حال با استفاده از دستور زیر می‌توانید یک کتابخانه را به سیستم اضافه‌کنید. (این دستور را باید در cmd و یا terminal اجرا کنید.)
</div>

<div style = "direction:rtl">
برای مثال می‌توانید کتابخانه pygame را با استفاده از همین دستور نصب کنید. (توجه‌کنید که چون از پایتون۳ استفاده می‌کنیم باید در ترمینال هم از pip3 استفاده‌کنیم.)
<br>
همچنین با استفاده از دستور زیر می‌توانید همه کتابخانه‌هایی که در سیستم موجود است را به همراه نسخه‌ای که دارند مشاهده‌کنید.
</div>

<div style = "direction:rtl">
در لیست بالا می‌توانید برخی از کتابخانه‌هایی که خروجی داده‌شدند را مشاهده کنید. مقدار درون پرانتز نسخه آن کتابخانه را نشان می‌دهد.
<br>
همچنین با استفاده از دستور uninstall می‌توانید یک package نصب‌شده را از سیستم حذف کنید.
</div>

<div style = "direction:rtl">
برای مثال در نمونه‌ی بالا کتابخانه pygame را که نصب کردیم حذف می‌کنیم.
<br>
برای اطلاع از قابلیت‌های بیشتر pip می‌‌توانید با نوشتن دستور زیر در ترمینال، در خروجی اطلاعت مفیدی در این مورد دریافت کنید.
</div>

---------------------------
### 2.13. Virtual Environment

https://quera.ir/college/3078/chapter/9151/lesson/31129/?comments_page=1&comments_filter=ALL

---------------------------------------